/* =========================================================================
 * Type_TY AVAS L1 line model -- FIXED-POINT coefficient tables for dsPIC33CK
 * GENERATED by tools/gen_avas_type_ty_ck_tables.py -- DO NOT EDIT
 *
 * Source of the coefficients:
 *     tools/host_check/ref/avas_synth_type_ty_tables.h
 * Source of every derived integer below:
 *     tools/avas_type_ty_fixed_model.py  (imported by the generator, so the model
 *     that measured this design and the firmware that runs it share one set of
 *     numbers by construction)
 *
 * Design point, as measured by that model against the offline reference:
 *     185 lines, 11 clusters, DEC=32, 512-entry Q15 sine table, 16-bit interpolation
 *     48.1 dB below signal, line-free floor -85.0 dBFS
 *   (the AK float engine it ports: 48.9 dB, -71.9 dBFS -- so this is parity on
 *    accuracy and 13 dB better on the noise floor, because a Q15 interpolated
 *    table beats the parabolic sine approximation AK uses -- 7 dB of that is the
 *    table, the rest is OUTPUT_TRIM_DB's deliberate -6.0 dB below AK-parity peak,
 *    which shifts the ratio's floor and ceiling together and leaves 48.1 dB itself
 *    unmoved)
 *
 * fs is BAKED IN: bb_step and car_step are both scaled by it.  A rate change cannot
 * pass silently -- regenerate instead.  What catches it is avas_rate_matches() in
 * wm8904_audio.c, at RUN time, because the rate is a runtime property of the
 * transport config; avas_type_ty_ck.h also offers an opt-in #error, but nothing in this
 * project defines the macro it needs.  See that header's SAMPLE RATE section.
 * ========================================================================= */

#ifndef AVAS_TYPE_TY_CK_TABLES_H
#define AVAS_TYPE_TY_CK_TABLES_H

#include <stdint.h>

#define AVAS_TYPE_TY_CK_TABLE_FS_HZ    (48000u)
#define AVAS_TYPE_TY_CK_LINES          (185u)
#define AVAS_TYPE_TY_CK_CLUSTERS       (11u)
#define AVAS_TYPE_TY_CK_DEC            (32u)
#define AVAS_TYPE_TY_CK_DECSHIFT       (5u)   /* log2(DEC): the slope divide is a shift */
#define AVAS_TYPE_TY_CK_TABBITS        (9u)
#define AVAS_TYPE_TY_CK_TABN           (512u)
#define AVAS_TYPE_TY_CK_FRACBITS       (16u)
#define AVAS_TYPE_TY_CK_IDXSHIFT       (23u)   /* 32 - TABBITS */
#define AVAS_TYPE_TY_CK_FRACSHIFT      (7u)   /* 32 - TABBITS - FRACBITS */
#define AVAS_TYPE_TY_CK_TERMSHIFT      (4u)   /* per-carrier shift before summing y */

/* The engine splits the phase into an index and a fraction using 16-bit
 * operations only, so these are stated relative to the phase's HIGH WORD rather
 * than to the 32-bit accumulator.  The point is that nothing in the per-sample
 * path performs a 32-bit shift: idx is one lsr of the high word, and the
 * fraction is the remaining bits of the high word joined to the top of the low
 * word.  (FRACBITS is 16 for the same reason -- see the model's note.) */
#define AVAS_TYPE_TY_CK_IDXSHIFT_HI    (7u)   /* 16 - TABBITS */
#define AVAS_TYPE_TY_CK_TABMASK        (511u)   /* TABN - 1 */
#define AVAS_TYPE_TY_CK_QUARTER        (128u)   /* TABN/4: the cos index offset */

/* -------------------------------------------------------------------------
 * PHASE ACCUMULATOR WIDTHS -- a build-time choice, and BOTH step tables below are
 * generated for it.  AVAS_TYPE_TY_CK_PHBITS_BB is V1 (the 185 baseband oscillators),
 * AVAS_TYPE_TY_CK_PHBITS_CAR is V2 (the 11 full-rate carriers).
 *
 * THE DEFAULT IS 16/16 since the hardware gate closed: the block ISR measures
 * 368.5 us of its 667 us -- 54.9 %, margin 302.5 us, miss = 0 -- and the engine was
 * listened to through the board's own codec, amplifier and speaker and called
 * perfect.  Build 32/32 with -Define to get the width the early figures were
 * measured at; it is kept, proved and
 * flashable for the same reason ACC_MODE 0 is (it is the width a part with cycles to
 * spare should prefer -- the narrow one buys load with frequency resolution, and
 * only this line table and this listener say that trade is free).
 *
 * WHY IT IS CHEAPER.  On a 16-bit core a 16-bit accumulator is one add instead of
 * add/addc, and the index/fraction split stops having to join the two halves of a
 * 32-bit word -- which is the per-line cost this engine is made of.  V1 also
 * returns 2 bytes of RAM per line (370 B) and both shrink flash.
 *
 * WHAT IT COSTS: frequency RESOLUTION, because the step must be an integer --
 * fs/2^bits for a carrier, (fs/DEC)/2^bits for a baseband oscillator.  Realised
 * with THIS line table, computed by the model rather than bounded:
 *
 *     width      worst carrier error    worst baseband error    interp fraction
 *      32/32     0.000005             0.000000             16 bits
 *      16/16     0.362138             0.011403              7 bits
 *
 * (The fraction narrows because a 16-bit phase has only 16 - TABBITS bits left
 * below the index.  Measured identical to 16 bits on every figure; the resolution
 * is the whole cost.)
 *
 * HOW THAT WAS JUDGED, because the headline metric cannot do it: a baseband error
 * changes how a cluster's lines beat against each other, and that beating IS the
 * sound, so 48 dB-below-signal says nothing useful about it.  Six 60 s renders,
 * unlabelled, with the shipped engine hidden among them as an anchor
 * (tools/avas_type_ty_panel.py): indistinguishable, including 16/16.  Then the same
 * width was heard on the board itself, which is the criterion -- a full listen
 * through the speaker this engine drives, not an A/B and not a residual.  The metric
 * keeps its job as the DEFECT watchdog -- host_check still proves C == model bit for
 * bit at whatever width it is told -- but the number to compare against moves with
 * the width, and that is expected rather than a regression.
 * ------------------------------------------------------------------------- */
#ifndef AVAS_TYPE_TY_CK_PHBITS_CAR
#define AVAS_TYPE_TY_CK_PHBITS_CAR     (16)
#endif
#ifndef AVAS_TYPE_TY_CK_PHBITS_BB
#define AVAS_TYPE_TY_CK_PHBITS_BB      (16)
#endif
#if ((AVAS_TYPE_TY_CK_PHBITS_CAR) != 32) && ((AVAS_TYPE_TY_CK_PHBITS_CAR) != 16)
#error "AVAS_TYPE_TY_CK_PHBITS_CAR must be 32 or 16 -- those are the two step tables this header carries."
#endif
#if ((AVAS_TYPE_TY_CK_PHBITS_BB) != 32) && ((AVAS_TYPE_TY_CK_PHBITS_BB) != 16)
#error "AVAS_TYPE_TY_CK_PHBITS_BB must be 32 or 16 -- those are the two step tables this header carries."
#endif

/* -------------------------------------------------------------------------
 * WHICH COORDINATES THE ENVELOPE IS INTERPOLATED IN -- 0 rect, 1 polar, and the
 * same choice the model calls ENVINTERP=rect|polar.
 *
 *   0  rect   I_k*cos(theta) - Q_k*sin(theta).  TWO interpolated lookups, two
 *             multiplies and two 32-bit envelope adds per carrier per sample.
 *   1  polar  A_k*cos(theta + phi_k), with phi_k folded into that carrier's own
 *             phase accumulator so it costs no add of its own: ONE lookup, ONE
 *             multiply, ONE 32-bit add.  The rebuild pays a CORDIC per cluster
 *             (the table below) and the state loses env_q/env_dq.
 *
 * The identity is exact AT the rebuild instants; the difference is entirely in the
 * 32 samples between them.  A straight line in (I,Q) passes near the origin, so a
 * beat null is reproduced; a straight line in (A,phi) walks around the origin and
 * fills the null in.  MEASURED, and this is the whole reason this is a switch and
 * not a rewrite: the error is 1.8x larger and the line-free floor rises ~4 dB
 * (both the numbers and the load were measured), and then the ear did not hear
 * it -- 60 s blind, on this board's own
 * speaker, "honestly the same, both sound like the real Type_TY".  So the metric
 * rejects it, the criterion accepts it, and both records are kept.
 * ------------------------------------------------------------------------- */
#ifndef AVAS_TYPE_TY_CK_ENVINTERP
#define AVAS_TYPE_TY_CK_ENVINTERP      (1)
#endif
#if ((AVAS_TYPE_TY_CK_ENVINTERP) != 0) && ((AVAS_TYPE_TY_CK_ENVINTERP) != 1)
#error "AVAS_TYPE_TY_CK_ENVINTERP must be 0 (rect) or 1 (polar)."
#endif

/* -------------------------------------------------------------------------
 * HOW WIDE THE ENVELOPE STATE IS -- 16 fraction bits below the Q15 value, or none.
 * The model calls this ENVFRAC and the document calls it V3.
 *
 *   16  the state is an int32 whose TOP 16 BITS are the Q15 value, and the bottom
 *       16 carry the slope's fraction so a slow cluster's slope does not quantise.
 *   0   the state IS the int16 Q15 value: one word per interpolated quantity, one
 *       16-bit add per carrier per sample instead of a 32-bit one, and the read-out
 *       shift disappears because there is nothing below the value to shift off.
 *
 * WHY 0 IS NOT FREE, and this is the part that is easy to get wrong.  The slope is
 * (target - now) >> DECSHIFT and C's >> floors, so with no fraction bits a block
 * that needs to RISE by less than DEC freezes while one that needs to FALL by the
 * same amount moves a full DEC.  The truncation is not symmetric, the state settles
 * BELOW its target, and a constant on the envelope multiplies the carrier into a
 * spurious line at that cluster's own centroid -- coherent, so it costs far more on
 * the metric than its size suggests.  MEASURED: rect loses 6.3 dB, and polar instead
 * droops one cluster's level by 0.63 dB (its state holds a magnitude, where rect's
 * two signed components could let a floored I cancel a floored Q).
 *
 * That is what AVAS_TYPE_TY_CK_ENVROUND buys back, which is why the two knobs are not
 * independent: ENVROUND follows ENVFRAC unless it is overridden, and ENVFRAC=0 with
 * ENVROUND=0 is the variant the document measured AND REJECTED, kept reachable only
 * so that the rejection can be reproduced.  See section 19.
 *
 * 0 IS WHAT SHIPS, since section 25.  With ENVROUND on it costs 0.4 dB of the offline
 * metric and buys, MEASURED on the board against the wide state built from the same
 * commit: block ISR 298.9 -> 289.2 us (44.5 -> 43.0 per cent of the block), margin
 * 382.2 us, miss = 0, 135 B of flash and 44 B of RAM returned -- and the listener
 * passed it on this board's own speaker (section 24).  The 0.4 dB is recorded and did
 * not decide it, for the reason section 16 gives.  The wide state is still a build
 * away: -Define AVAS_TYPE_TY_CK_ENVFRAC=16 (ENVROUND then follows back to 0).
 * ------------------------------------------------------------------------- */
#ifndef AVAS_TYPE_TY_CK_ENVFRAC
#define AVAS_TYPE_TY_CK_ENVFRAC        (0)
#endif
#if ((AVAS_TYPE_TY_CK_ENVFRAC) != 16) && ((AVAS_TYPE_TY_CK_ENVFRAC) != 0)
#error "AVAS_TYPE_TY_CK_ENVFRAC must be 0 (V3, the shipped int16 state) or 16 (the wide 32-bit state)."
#endif

/* ROUNDING THE SLOPE: add DEC/2 before the shift, which makes the truncation above
 * zero-mean.  One add per interpolated quantity per cluster per REBUILD -- 11
 * instructions per DEC samples in polar, 22 in rect -- against the per-carrier
 * per-SAMPLE work that ENVFRAC=0 removes, so it is bought with small change.
 *
 * At ENVFRAC=16 it is a MEASURED NO-OP on the output samples (section 20: the slope's
 * LSB is 2**-16 of a Q15 count there, and the two floors that do bias the engine at
 * that width are the read-out and the target, not this one) -- so the shipped build,
 * which is ENVFRAC=0, is the one that needs it and the only one where it does work.
 *
 * The pairing is enforced rather than defaulted, which is this engine's habit for a
 * combination that would otherwise build quietly and be wrong: -Define ENVFRAC=0 on
 * its own does not silently get the floored variant, it does not compile.  Reproducing
 * the rejection is a MODEL run (tools/avas_type_ty_env16_study.py), not a firmware build,
 * so the firmware loses nothing by refusing to build it. */
#ifndef AVAS_TYPE_TY_CK_ENVROUND
#define AVAS_TYPE_TY_CK_ENVROUND       (1)
#endif
#if ((AVAS_TYPE_TY_CK_ENVROUND) != 0) && ((AVAS_TYPE_TY_CK_ENVROUND) != 1)
#error "AVAS_TYPE_TY_CK_ENVROUND must be 0 (floor, C's >>) or 1 (round, add DEC/2 first)."
#endif
#if ((AVAS_TYPE_TY_CK_ENVFRAC) == 0) && ((AVAS_TYPE_TY_CK_ENVROUND) == 0)
#error "ENVFRAC=0 (V3) needs ENVROUND=1: floored, the narrow state biases itself low -- rect loses 6.3 dB and polar droops a cluster by 0.63 dB (doc section 19).  Add AVAS_TYPE_TY_CK_ENVROUND=1."
#endif

/* The phase words, as NAMED TYPES rather than #if'd struct fields and #if'd
 * locals: the state, the step tables and the loop's copies then cannot disagree
 * about the width, which is the one way this change could go wrong silently.
 *
 * The signed twin is what reads a DIFFERENCE of two phases: polar's rebuild needs
 * `p_target - p_reached` as a signed value of the same width, which is the shortest
 * way round with no branch and no comparison -- the unwrap comes free out of the
 * same wrap-is-overflow property the phase itself relies on. */
#if ((AVAS_TYPE_TY_CK_PHBITS_CAR) == 16)
typedef uint16_t avas_type_ty_ck_carph_t;
typedef int16_t  avas_type_ty_ck_carph_signed_t;
#else
typedef uint32_t avas_type_ty_ck_carph_t;
typedef int32_t  avas_type_ty_ck_carph_signed_t;
#endif
#if ((AVAS_TYPE_TY_CK_PHBITS_BB) == 16)
typedef uint16_t avas_type_ty_ck_bbph_t;
typedef int16_t  avas_type_ty_ck_bbstep_t;
#else
typedef uint32_t avas_type_ty_ck_bbph_t;
typedef int32_t  avas_type_ty_ck_bbstep_t;
#endif

/* The envelope accumulator, as a NAMED TYPE for the same reason the phase words are:
 * the struct field, the loop's local copy and the rebuild's slope then cannot
 * disagree about the width.  int16 at ENVFRAC=0 -- and the wrap that the narrow type
 * brings with it is not incidental, it is what the model reproduces (_env()), because
 * V3's whole risk is what the low end of the state does. */
#if ((AVAS_TYPE_TY_CK_ENVFRAC) == 0)
typedef int16_t  avas_type_ty_ck_env_t;
#else
typedef int32_t  avas_type_ty_ck_env_t;
#endif

/* The three places the width shows through, written once here so the engine reads the
 * same at both widths and neither variant is a second copy of the loop.
 *
 *   _TGT   scale a Q15 target into the accumulator's units.  At 16 this is the `<< 16`
 *          that costs nothing (eval_cluster returns int16, so it is which register the
 *          value sits in); at 0 it is nothing at all.  int32 EITHER WAY, so that the
 *          difference below cannot overflow: two Q15 values can differ by 65534, and
 *          the model computes that difference in full width before it shifts.
 *   _Q15   take the Q15 value back out for the multiply -- the high word, or the value.
 *   _SLOPE (target - now) >> DECSHIFT, rounded per ENVROUND, wrapped to the state's
 *          width by the cast, which is the model's _env() on the same expression.
 *   _ADD   the per-sample accumulate, and the ONE place the two widths need different
 *          text rather than a different constant.  At 16 it is the signed add this
 *          engine has always done.  At 0 the sum can leave int16 (a target near full
 *          scale plus one slope step), and the model WRAPS there -- so it is spelled as
 *          an unsigned add, which is the only wrap C defines, and read back signed by
 *          the same modulo-2^width cast the phase unwrap in the engine rests on.  One
 *          instruction either way; host_check is what proves the two agree. */
#define AVAS_TYPE_TY_CK_ENV_TGT(z)     (((int32_t)(z)) << (AVAS_TYPE_TY_CK_ENVFRAC))
#define AVAS_TYPE_TY_CK_ENV_Q15(e)     ((int16_t)((e) >> (AVAS_TYPE_TY_CK_ENVFRAC)))
#define AVAS_TYPE_TY_CK_ENV_RND \
    ((AVAS_TYPE_TY_CK_ENVROUND) ? (int32_t)((AVAS_TYPE_TY_CK_DEC) / 2u) : (int32_t)0)
#define AVAS_TYPE_TY_CK_ENV_SLOPE(tgt, now)                                      \
    ((avas_type_ty_ck_env_t)((((tgt) - (int32_t)(now)) + (AVAS_TYPE_TY_CK_ENV_RND))  \
                          >> (AVAS_TYPE_TY_CK_DECSHIFT)))
#if ((AVAS_TYPE_TY_CK_ENVFRAC) == 0)
#define AVAS_TYPE_TY_CK_ENV_ADD(e, d)  \
    ((int16_t)(uint16_t)((uint16_t)(e) + (uint16_t)(d)))
#else
#define AVAS_TYPE_TY_CK_ENV_ADD(e, d)  ((int32_t)(e) + (int32_t)(d))
#endif

/* Maps the accumulated y (in the scaled units the amplitude table uses) to Q15
 * output, reproducing the AK engine's level -- the measured 60 s peak of the full
 * 185-line sum normalised to 0.9 of full scale -- and then trimmed OUTPUT_TRIM_DB
 * (-6.0 dB) below that AK-parity peak, by request. Regenerate rather than hand-edit:
 * the generator computes this from the model's own OUT_GAIN_Q15, so the two numbers
 * cannot drift apart. */
#define AVAS_TYPE_TY_CK_NORM_GAIN_Q15  (14401)

/* The gain's left SHIFT, which is 0 for this set and is stated rather than assumed.
 * A_SCALE is set by the worst CLUSTER's amplitude sum while the gain's numerator is
 * the peak the WHOLE sum reaches; with 11 narrow clusters those are nearly equal
 * (0.3758 against 0.3858, ratio 1.026), so the gain is 0.877 and Q15 holds it.  A
 * coefficient set whose clusters are fat does NOT get that for free -- the
 * Type_LB's is such a set at some spans -- so the shift is part of a voice's
 * table and the engine reads it from whichever voice is selected.  At 0 the output
 * path is the single `>> 15` this engine has always done. */
#define AVAS_TYPE_TY_CK_NORM_SHIFT     (0)

/* Gate one-pole, attack 4.000 s / release 0.500 s at 48000 Hz.  See the generator for
 * why this is an int16 numerator and a shift rather than a Q31 multiply. */
#define AVAS_TYPE_TY_CK_GATE_ALPHA_SHIFT   (27u)
#define AVAS_TYPE_TY_CK_GATE_ATTACK_NUM    (699)
#define AVAS_TYPE_TY_CK_GATE_RELEASE_NUM   (5592)
#define AVAS_TYPE_TY_CK_GATE_EPS_Q31       (6790988L)

/* -------------------------------------------------------------------------
 * Q15 sine, one full cycle, as {value, delta-to-next} PAIRS.
 *
 * The pair form is what makes the interpolation cheap, and the reason is the
 * instruction set rather than the algorithm: a 4-byte aligned pair is ONE mov.d,
 * where reading tab[idx] and tab[idx+1] separately costs two address
 * computations, two loads, two sign extends and a 32-bit subtract.  Measured on
 * XC-DSC 3.31.01 for 33CK64MC105, one interpolated lookup went from 22
 * instructions to 6.
 *
 * cos is this same table read a quarter cycle further along, which at this
 * geometry is the exact index offset AVAS_TYPE_TY_CK_TABN/4 -- so cos and sin share
 * one phase accumulator AND one interpolation fraction, and the quarter-cycle
 * add disappears from the per-sample path entirely.
 *
 * The table therefore runs TABN + TABN/4 entries: the first TABN/4 are repeated
 * past the end so that `idx + QUARTER` NEVER NEEDS A WRAP MASK.  That costs 512
 * bytes of flash (of ~23 KB free) and removes an and-with-511 plus the register
 * holding the mask from the per-carrier path.  Delta fits int16 with room to
 * spare: the largest step of a Q15 sine sampled 512 times is 402.
 * ------------------------------------------------------------------------- */
typedef struct
{
    int16_t v;      /* Q15 sine at this index          */
    int16_t d;      /* Q15 sine at index+1, minus v    */
} avas_type_ty_ck_sin_ent_t;

#define AVAS_TYPE_TY_CK_TABENTS    (AVAS_TYPE_TY_CK_TABN + AVAS_TYPE_TY_CK_QUARTER)

/* aligned(4): the pair is fetched as a 32-bit double word. */
static const avas_type_ty_ck_sin_ent_t s_ck_sin_dq15[AVAS_TYPE_TY_CK_TABENTS]
    __attribute__((aligned(4))) = {
    {      0,   402 }, {    402,   402 }, {    804,   402 }, {   1206,   402 },
    {   1608,   401 }, {   2009,   401 }, {   2410,   401 }, {   2811,   401 },
    {   3212,   400 }, {   3612,   399 }, {   4011,   399 }, {   4410,   398 },
    {   4808,   397 }, {   5205,   397 }, {   5602,   396 }, {   5998,   395 },
    {   6393,   393 }, {   6786,   393 }, {   7179,   392 }, {   7571,   391 },
    {   7962,   389 }, {   8351,   388 }, {   8739,   387 }, {   9126,   386 },
    {   9512,   384 }, {   9896,   382 }, {  10278,   381 }, {  10659,   380 },
    {  11039,   378 }, {  11417,   376 }, {  11793,   374 }, {  12167,   372 },
    {  12539,   371 }, {  12910,   369 }, {  13279,   366 }, {  13645,   365 },
    {  14010,   362 }, {  14372,   360 }, {  14732,   358 }, {  15090,   356 },
    {  15446,   354 }, {  15800,   351 }, {  16151,   348 }, {  16499,   347 },
    {  16846,   343 }, {  17189,   341 }, {  17530,   339 }, {  17869,   335 },
    {  18204,   333 }, {  18537,   331 }, {  18868,   327 }, {  19195,   324 },
    {  19519,   322 }, {  19841,   318 }, {  20159,   316 }, {  20475,   312 },
    {  20787,   309 }, {  21096,   307 }, {  21403,   302 }, {  21705,   300 },
    {  22005,   296 }, {  22301,   293 }, {  22594,   290 }, {  22884,   286 },
    {  23170,   282 }, {  23452,   279 }, {  23731,   276 }, {  24007,   272 },
    {  24279,   268 }, {  24547,   264 }, {  24811,   261 }, {  25072,   257 },
    {  25329,   253 }, {  25582,   250 }, {  25832,   245 }, {  26077,   242 },
    {  26319,   237 }, {  26556,   234 }, {  26790,   229 }, {  27019,   226 },
    {  27245,   221 }, {  27466,   217 }, {  27683,   213 }, {  27896,   209 },
    {  28105,   205 }, {  28310,   200 }, {  28510,   196 }, {  28706,   192 },
    {  28898,   187 }, {  29085,   183 }, {  29268,   179 }, {  29447,   174 },
    {  29621,   170 }, {  29791,   165 }, {  29956,   161 }, {  30117,   156 },
    {  30273,   151 }, {  30424,   147 }, {  30571,   143 }, {  30714,   138 },
    {  30852,   133 }, {  30985,   128 }, {  31113,   124 }, {  31237,   119 },
    {  31356,   114 }, {  31470,   110 }, {  31580,   105 }, {  31685,   100 },
    {  31785,    95 }, {  31880,    91 }, {  31971,    86 }, {  32057,    80 },
    {  32137,    76 }, {  32213,    72 }, {  32285,    66 }, {  32351,    61 },
    {  32412,    57 }, {  32469,    52 }, {  32521,    46 }, {  32567,    42 },
    {  32609,    37 }, {  32646,    32 }, {  32678,    27 }, {  32705,    23 },
    {  32728,    17 }, {  32745,    12 }, {  32757,     8 }, {  32765,     2 },
    {  32767,    -2 }, {  32765,    -8 }, {  32757,   -12 }, {  32745,   -17 },
    {  32728,   -23 }, {  32705,   -27 }, {  32678,   -32 }, {  32646,   -37 },
    {  32609,   -42 }, {  32567,   -46 }, {  32521,   -52 }, {  32469,   -57 },
    {  32412,   -61 }, {  32351,   -66 }, {  32285,   -72 }, {  32213,   -76 },
    {  32137,   -80 }, {  32057,   -86 }, {  31971,   -91 }, {  31880,   -95 },
    {  31785,  -100 }, {  31685,  -105 }, {  31580,  -110 }, {  31470,  -114 },
    {  31356,  -119 }, {  31237,  -124 }, {  31113,  -128 }, {  30985,  -133 },
    {  30852,  -138 }, {  30714,  -143 }, {  30571,  -147 }, {  30424,  -151 },
    {  30273,  -156 }, {  30117,  -161 }, {  29956,  -165 }, {  29791,  -170 },
    {  29621,  -174 }, {  29447,  -179 }, {  29268,  -183 }, {  29085,  -187 },
    {  28898,  -192 }, {  28706,  -196 }, {  28510,  -200 }, {  28310,  -205 },
    {  28105,  -209 }, {  27896,  -213 }, {  27683,  -217 }, {  27466,  -221 },
    {  27245,  -226 }, {  27019,  -229 }, {  26790,  -234 }, {  26556,  -237 },
    {  26319,  -242 }, {  26077,  -245 }, {  25832,  -250 }, {  25582,  -253 },
    {  25329,  -257 }, {  25072,  -261 }, {  24811,  -264 }, {  24547,  -268 },
    {  24279,  -272 }, {  24007,  -276 }, {  23731,  -279 }, {  23452,  -282 },
    {  23170,  -286 }, {  22884,  -290 }, {  22594,  -293 }, {  22301,  -296 },
    {  22005,  -300 }, {  21705,  -302 }, {  21403,  -307 }, {  21096,  -309 },
    {  20787,  -312 }, {  20475,  -316 }, {  20159,  -318 }, {  19841,  -322 },
    {  19519,  -324 }, {  19195,  -327 }, {  18868,  -331 }, {  18537,  -333 },
    {  18204,  -335 }, {  17869,  -339 }, {  17530,  -341 }, {  17189,  -343 },
    {  16846,  -347 }, {  16499,  -348 }, {  16151,  -351 }, {  15800,  -354 },
    {  15446,  -356 }, {  15090,  -358 }, {  14732,  -360 }, {  14372,  -362 },
    {  14010,  -365 }, {  13645,  -366 }, {  13279,  -369 }, {  12910,  -371 },
    {  12539,  -372 }, {  12167,  -374 }, {  11793,  -376 }, {  11417,  -378 },
    {  11039,  -380 }, {  10659,  -381 }, {  10278,  -382 }, {   9896,  -384 },
    {   9512,  -386 }, {   9126,  -387 }, {   8739,  -388 }, {   8351,  -389 },
    {   7962,  -391 }, {   7571,  -392 }, {   7179,  -393 }, {   6786,  -393 },
    {   6393,  -395 }, {   5998,  -396 }, {   5602,  -397 }, {   5205,  -397 },
    {   4808,  -398 }, {   4410,  -399 }, {   4011,  -399 }, {   3612,  -400 },
    {   3212,  -401 }, {   2811,  -401 }, {   2410,  -401 }, {   2009,  -401 },
    {   1608,  -402 }, {   1206,  -402 }, {    804,  -402 }, {    402,  -402 },
    {      0,  -402 }, {   -402,  -402 }, {   -804,  -402 }, {  -1206,  -402 },
    {  -1608,  -401 }, {  -2009,  -401 }, {  -2410,  -401 }, {  -2811,  -401 },
    {  -3212,  -400 }, {  -3612,  -399 }, {  -4011,  -399 }, {  -4410,  -398 },
    {  -4808,  -397 }, {  -5205,  -397 }, {  -5602,  -396 }, {  -5998,  -395 },
    {  -6393,  -393 }, {  -6786,  -393 }, {  -7179,  -392 }, {  -7571,  -391 },
    {  -7962,  -389 }, {  -8351,  -388 }, {  -8739,  -387 }, {  -9126,  -386 },
    {  -9512,  -384 }, {  -9896,  -382 }, { -10278,  -381 }, { -10659,  -380 },
    { -11039,  -378 }, { -11417,  -376 }, { -11793,  -374 }, { -12167,  -372 },
    { -12539,  -371 }, { -12910,  -369 }, { -13279,  -366 }, { -13645,  -365 },
    { -14010,  -362 }, { -14372,  -360 }, { -14732,  -358 }, { -15090,  -356 },
    { -15446,  -354 }, { -15800,  -351 }, { -16151,  -348 }, { -16499,  -347 },
    { -16846,  -343 }, { -17189,  -341 }, { -17530,  -339 }, { -17869,  -335 },
    { -18204,  -333 }, { -18537,  -331 }, { -18868,  -327 }, { -19195,  -324 },
    { -19519,  -322 }, { -19841,  -318 }, { -20159,  -316 }, { -20475,  -312 },
    { -20787,  -309 }, { -21096,  -307 }, { -21403,  -302 }, { -21705,  -300 },
    { -22005,  -296 }, { -22301,  -293 }, { -22594,  -290 }, { -22884,  -286 },
    { -23170,  -282 }, { -23452,  -279 }, { -23731,  -276 }, { -24007,  -272 },
    { -24279,  -268 }, { -24547,  -264 }, { -24811,  -261 }, { -25072,  -257 },
    { -25329,  -253 }, { -25582,  -250 }, { -25832,  -245 }, { -26077,  -242 },
    { -26319,  -237 }, { -26556,  -234 }, { -26790,  -229 }, { -27019,  -226 },
    { -27245,  -221 }, { -27466,  -217 }, { -27683,  -213 }, { -27896,  -209 },
    { -28105,  -205 }, { -28310,  -200 }, { -28510,  -196 }, { -28706,  -192 },
    { -28898,  -187 }, { -29085,  -183 }, { -29268,  -179 }, { -29447,  -174 },
    { -29621,  -170 }, { -29791,  -165 }, { -29956,  -161 }, { -30117,  -156 },
    { -30273,  -151 }, { -30424,  -147 }, { -30571,  -143 }, { -30714,  -138 },
    { -30852,  -133 }, { -30985,  -128 }, { -31113,  -124 }, { -31237,  -119 },
    { -31356,  -114 }, { -31470,  -110 }, { -31580,  -105 }, { -31685,  -100 },
    { -31785,   -95 }, { -31880,   -91 }, { -31971,   -86 }, { -32057,   -80 },
    { -32137,   -76 }, { -32213,   -72 }, { -32285,   -66 }, { -32351,   -61 },
    { -32412,   -57 }, { -32469,   -52 }, { -32521,   -46 }, { -32567,   -42 },
    { -32609,   -37 }, { -32646,   -32 }, { -32678,   -27 }, { -32705,   -23 },
    { -32728,   -17 }, { -32745,   -12 }, { -32757,    -8 }, { -32765,    -2 },
    { -32767,     2 }, { -32765,     8 }, { -32757,    12 }, { -32745,    17 },
    { -32728,    23 }, { -32705,    27 }, { -32678,    32 }, { -32646,    37 },
    { -32609,    42 }, { -32567,    46 }, { -32521,    52 }, { -32469,    57 },
    { -32412,    61 }, { -32351,    66 }, { -32285,    72 }, { -32213,    76 },
    { -32137,    80 }, { -32057,    86 }, { -31971,    91 }, { -31880,    95 },
    { -31785,   100 }, { -31685,   105 }, { -31580,   110 }, { -31470,   114 },
    { -31356,   119 }, { -31237,   124 }, { -31113,   128 }, { -30985,   133 },
    { -30852,   138 }, { -30714,   143 }, { -30571,   147 }, { -30424,   151 },
    { -30273,   156 }, { -30117,   161 }, { -29956,   165 }, { -29791,   170 },
    { -29621,   174 }, { -29447,   179 }, { -29268,   183 }, { -29085,   187 },
    { -28898,   192 }, { -28706,   196 }, { -28510,   200 }, { -28310,   205 },
    { -28105,   209 }, { -27896,   213 }, { -27683,   217 }, { -27466,   221 },
    { -27245,   226 }, { -27019,   229 }, { -26790,   234 }, { -26556,   237 },
    { -26319,   242 }, { -26077,   245 }, { -25832,   250 }, { -25582,   253 },
    { -25329,   257 }, { -25072,   261 }, { -24811,   264 }, { -24547,   268 },
    { -24279,   272 }, { -24007,   276 }, { -23731,   279 }, { -23452,   282 },
    { -23170,   286 }, { -22884,   290 }, { -22594,   293 }, { -22301,   296 },
    { -22005,   300 }, { -21705,   302 }, { -21403,   307 }, { -21096,   309 },
    { -20787,   312 }, { -20475,   316 }, { -20159,   318 }, { -19841,   322 },
    { -19519,   324 }, { -19195,   327 }, { -18868,   331 }, { -18537,   333 },
    { -18204,   335 }, { -17869,   339 }, { -17530,   341 }, { -17189,   343 },
    { -16846,   347 }, { -16499,   348 }, { -16151,   351 }, { -15800,   354 },
    { -15446,   356 }, { -15090,   358 }, { -14732,   360 }, { -14372,   362 },
    { -14010,   365 }, { -13645,   366 }, { -13279,   369 }, { -12910,   371 },
    { -12539,   372 }, { -12167,   374 }, { -11793,   376 }, { -11417,   378 },
    { -11039,   380 }, { -10659,   381 }, { -10278,   382 }, {  -9896,   384 },
    {  -9512,   386 }, {  -9126,   387 }, {  -8739,   388 }, {  -8351,   389 },
    {  -7962,   391 }, {  -7571,   392 }, {  -7179,   393 }, {  -6786,   393 },
    {  -6393,   395 }, {  -5998,   396 }, {  -5602,   397 }, {  -5205,   397 },
    {  -4808,   398 }, {  -4410,   399 }, {  -4011,   399 }, {  -3612,   400 },
    {  -3212,   401 }, {  -2811,   401 }, {  -2410,   401 }, {  -2009,   401 },
    {  -1608,   402 }, {  -1206,   402 }, {   -804,   402 }, {   -402,   402 },
    {      0,   402 }, {    402,   402 }, {    804,   402 }, {   1206,   402 },
    {   1608,   401 }, {   2009,   401 }, {   2410,   401 }, {   2811,   401 },
    {   3212,   400 }, {   3612,   399 }, {   4011,   399 }, {   4410,   398 },
    {   4808,   397 }, {   5205,   397 }, {   5602,   396 }, {   5998,   395 },
    {   6393,   393 }, {   6786,   393 }, {   7179,   392 }, {   7571,   391 },
    {   7962,   389 }, {   8351,   388 }, {   8739,   387 }, {   9126,   386 },
    {   9512,   384 }, {   9896,   382 }, {  10278,   381 }, {  10659,   380 },
    {  11039,   378 }, {  11417,   376 }, {  11793,   374 }, {  12167,   372 },
    {  12539,   371 }, {  12910,   369 }, {  13279,   366 }, {  13645,   365 },
    {  14010,   362 }, {  14372,   360 }, {  14732,   358 }, {  15090,   356 },
    {  15446,   354 }, {  15800,   351 }, {  16151,   348 }, {  16499,   347 },
    {  16846,   343 }, {  17189,   341 }, {  17530,   339 }, {  17869,   335 },
    {  18204,   333 }, {  18537,   331 }, {  18868,   327 }, {  19195,   324 },
    {  19519,   322 }, {  19841,   318 }, {  20159,   316 }, {  20475,   312 },
    {  20787,   309 }, {  21096,   307 }, {  21403,   302 }, {  21705,   300 },
    {  22005,   296 }, {  22301,   293 }, {  22594,   290 }, {  22884,   286 },
    {  23170,   282 }, {  23452,   279 }, {  23731,   276 }, {  24007,   272 },
    {  24279,   268 }, {  24547,   264 }, {  24811,   261 }, {  25072,   257 },
    {  25329,   253 }, {  25582,   250 }, {  25832,   245 }, {  26077,   242 },
    {  26319,   237 }, {  26556,   234 }, {  26790,   229 }, {  27019,   226 },
    {  27245,   221 }, {  27466,   217 }, {  27683,   213 }, {  27896,   209 },
    {  28105,   205 }, {  28310,   200 }, {  28510,   196 }, {  28706,   192 },
    {  28898,   187 }, {  29085,   183 }, {  29268,   179 }, {  29447,   174 },
    {  29621,   170 }, {  29791,   165 }, {  29956,   161 }, {  30117,   156 },
    {  30273,   151 }, {  30424,   147 }, {  30571,   143 }, {  30714,   138 },
    {  30852,   133 }, {  30985,   128 }, {  31113,   124 }, {  31237,   119 },
    {  31356,   114 }, {  31470,   110 }, {  31580,   105 }, {  31685,   100 },
    {  31785,    95 }, {  31880,    91 }, {  31971,    86 }, {  32057,    80 },
    {  32137,    76 }, {  32213,    72 }, {  32285,    66 }, {  32351,    61 },
    {  32412,    57 }, {  32469,    52 }, {  32521,    46 }, {  32567,    42 },
    {  32609,    37 }, {  32646,    32 }, {  32678,    27 }, {  32705,    23 },
    {  32728,    17 }, {  32745,    12 }, {  32757,     8 }, {  32765,     2 },
};

/* -------------------------------------------------------------------------
 * THE TYPE_TY L1 COEFFICIENT SET ITSELF -- five arrays, and the ONLY part of this
 * header that is vehicle-specific.  Everything above and below (the knobs, the sine
 * table, the CORDIC constants, the gate) is shared with the Type_LB voice.
 *
 * IT IS COMPILED OUT OF A TYPE_LB IMAGE, and by the preprocessor rather than by
 * the linker, because that is the only thing that actually frees the bytes:
 * --gc-sections is on but -fdata-sections is deliberately off, so unreferenced
 * `const` inside a live translation unit is not collected -- MEASURED from the other
 * side.  1 156 data bytes = 1 734 program bytes, on an image at 99 % of flash.
 * ------------------------------------------------------------------------- */
/* AVAS_CK_VOICE_NONE is the debug mode (see avas_synth_line_ck.h): no voice is
 * compiled, so these arrays go too -- they are the bulk of what that mode reclaims.
 * Tested raw rather than through AVAS_LINE_CK_HAVE_ENGINE so that this header stays
 * usable on its own (generators, tools/host_check): an undefined macro reads as 0,
 * which is the permissive answer. */
#if !(AVAS_CK_VOICE_NONE) && (!(AVAS_CK_VOICE_TYPE_LB) || (AVAS_CK_VOICE_BOTH))

/* -------------------------------------------------------------------------
 * Per line, frequency ascending.  Each cluster is a contiguous run, which is
 * why no per-line cluster index exists.
 *
 *   amp_q15  amplitude, scaled so the strongest cluster's amplitude SUM fills
 *            Q15.  That bound is what makes |Z_k| <= 32767 and lets the
 *            envelope accumulate in a plain int32.
 *   bb_step  (f - fc)*DEC/fs as a phase increment, signed: lines below their
 *            carrier rotate backwards.  Derived here rather than in the firmware,
 *            so it costs flash instead of RAM.
 *   bb_pha0  the measured cos phase, as a whole cycle of 2^PHBITS_BB.
 *
 * Both are rounded FROM THE FREQUENCY at the selected width -- the narrow set is
 * not the wide set shifted down, because those two disagree by an LSB on plenty of
 * lines and host_check is bit-exact.
 * ------------------------------------------------------------------------- */
static const int16_t s_ck_amp_q15[AVAS_TYPE_TY_CK_LINES] = {
       130,    136,    197,    123,    167,    168,    153,    151,    131,    147,
       159,    171,    119,    127,    124,    128,    128,    139,    137,    268,
       157,    296,    267,    134,    107,    329,    468,    181,    184,    246,
       189,    110,    171,    227,    194,    176,    146,    181,    331,    293,
       168,    209,    343,    542,    895,   1301,   3307,   2208,   1372,   1206,
       250,    249,    197,    195,    196,    331,    167,    286,    169,    110,
       145,    137,    138,    348,    688,    496,    723,    828,   1186,    885,
      2070,   1696,   1609,   1754,   2411,   2427,   2521,   3501,   7552,   3007,
       835,    586,    254,    264,    137,    382,    526,    291,    266,    376,
       254,    276,    264,    243,    148,    133,    134,    106,    164,    214,
       222,    106,    128,    137,    116,    137,    118,    106,    160,    131,
       124,    142,    106,    129,    135,    117,    142,    141,    244,    188,
       169,    213,    170,    187,    136,    127,    144,    115,    111,    119,
       118,    127,    154,    230,    219,    242,    461,    309,    642,    870,
       802,    528,    280,    292,    198,    190,    184,    173,    181,    220,
       255,    332,    439,    354,    356,    367,    309,    308,    209,    288,
       190,    214,    207,    177,    132,    175,    147,    126,    252,    194,
       177,    136,    140,    165,    116,    106,    133,    154,    117,    284,
       228,    160,    106,    131,    117,
};

static const avas_type_ty_ck_bbstep_t s_ck_bb_step[AVAS_TYPE_TY_CK_LINES] = {
#if ((AVAS_TYPE_TY_CK_PHBITS_BB) == 16)
      -3201,   -2952,   -2891,   -2795,   -2623,   -2580,   -1979,   -1909,   -1782,   -1703,
      -1569,   -1055,    -813,     508,    1091,    1122,    1481,    1636,    2047,    2098,
       2186,    2424,    2467,    2530,    4997,   -5822,   -5728,   -5540,   -5428,   -5290,
      -5144,   -4350,   -4177,   -4136,   -4045,   -3976,   -1921,   -1848,   -1695,   -1532,
       -828,    -589,     387,     870,     940,    1032,    1175,    1239,    1381,    1499,
       2499,    2551,   -6942,   -6885,   -6795,   -6691,   -6645,   -6467,   -6380,   -5740,
      -4232,   -3808,   -3715,   -3040,   -2754,   -2657,   -2385,   -1698,   -1558,   -1506,
      -1449,   -1365,   -1147,     409,    1319,    1404,    1539,    1681,    1754,   -2664,
      -1381,   -1142,     481,     726,     828,    1800,    2111,    2397,    2445,    2492,
       2540,    2939,    2991,    3521,    3896,    4014,    4184,    5187,   -4530,   -4456,
      -4362,   -2090,     656,     765,    2471,    2552,    2615,    2768,    3338,    3546,
       3692,   -3492,   -2356,   -2199,   -2113,   -2022,   -1516,   -1200,    -833,    -540,
       -268,    -174,      74,     796,    1765,    2004,    3064,    3485,    3535,    3660,
      -4491,   -4252,   -3857,   -3725,   -3650,   -3485,   -2781,   -2644,   -1392,   -1330,
      -1284,   -1052,    -521,    -433,       7,     197,     503,    1455,    1521,    1637,
       2050,    2591,    2771,    3359,    3623,    4059,    4133,    4234,   -2468,   -2073,
      -1146,   -1064,      67,     649,    1620,    2364,    2749,    3141,   -1783,   -1513,
      -1243,   -1172,    -946,    -850,    -496,    5824,    6318,   -1257,     -48,      74,
        276,     377,     517,    -203,     228,
#else
      -209804857,   -193494576,   -189454730,   -183175201,   -171905493,   -169068524,
      -129690260,   -125103235,   -116805072,   -111588404,   -102856163,    -69142102,
       -53302835,     33274830,     71512064,     73505788,     97036196,    107198948,
       134142709,    137481044,    143247754,    158848220,    161681467,    165829260,
       327456610,   -381521086,   -375401617,   -363095104,   -355761304,   -346695487,
      -337123723,   -285077023,   -273735732,   -271072566,   -265060471,   -260562495,
      -125886637,   -121141557,   -111066995,   -100376249,    -54282087,    -38605170,
        25368081,     57045756,     61599280,     67636000,     77032815,     81229571,
        90532757,     98218457,    163760517,    167160986,   -454924368,   -451217238,
      -445327120,   -438513011,   -435485632,   -423852856,   -418133105,   -376161539,
      -277345795,   -249576541,   -243436456,   -199219481,   -180462500,   -174106521,
      -156301018,   -111255115,   -102103112,    -98698348,    -94985492,    -89441262,
       -75157060,     26812908,     86456833,     92033705,    100841251,    110178796,
       114979710,   -174590707,    -90500115,    -74855840,     31496141,     47583943,
        54269775,    117971298,    138320281,    157087856,    160236926,    163325580,
       166472646,    192630715,    196031184,    230761435,    255315763,    263048708,
       274192144,    339921178,   -296891332,   -292045750,   -285896789,   -137000008,
        42988900,     50160350,    161971807,    167267788,    171394965,    181408252,
       218763014,    232386364,    241951256,   -228847311,   -154417818,   -144085845,
      -138456002,   -132503177,    -99334863,    -78646005,    -54570136,    -35394253,
       -17557540,    -11390253,      4845009,     52150925,    115643712,    131336950,
       200828662,    228361693,    231684853,    239893108,   -294341267,   -278679526,
      -252782591,   -244139685,   -239191310,   -228396912,   -182230595,   -173295631,
       -91240854,    -87143455,    -84142704,    -68971448,    -34161597,    -28371409,
          438087,     12935869,     32990503,     95342261,     99656985,    107304318,
       134341709,    169778339,    181622427,    220147711,    237431805,    265987611,
       270835197,    277447729,   -161757058,   -135878735,    -75108384,    -69753419,
         4416085,     42508150,    106185622,    154951539,    180137228,    205828290,
      -116882667,    -99163064,    -81460640,    -76786857,    -61965784,    -55719183,
       -32521779,    381691167,    414024539,    -82353994,     -3160237,      4840714,
        18058333,     24724122,     33851214,    -13309817,     14935892,
#endif
};

static const avas_type_ty_ck_bbph_t s_ck_bb_pha0[AVAS_TYPE_TY_CK_LINES] = {
#if ((AVAS_TYPE_TY_CK_PHBITS_BB) == 16)
     24707u,  11708u,  12930u,  52433u,  31675u,  14628u,  28286u,    770u,  15156u,  19564u,
     41951u,  54627u,   6348u,  32733u,  60796u,    722u,   8322u,   3741u,  65063u,  40497u,
     10549u,  63322u,  24597u,   9622u,  19188u,  23166u,  39170u,  26083u,  15465u,  45014u,
     60047u,   4848u,  29935u,  55831u,  61163u,  12154u,  32467u,  13296u,  36023u,  14168u,
      1407u,  38118u,  53518u,  17247u,   4460u,   4938u,  63593u,  18423u,   6378u,  59633u,
     11257u,  20938u,   4647u,   8589u,   4202u,  55055u,  17149u,  20468u,  51545u,   7236u,
     53144u,  41969u,  45489u,  28081u,  18726u,  18676u,  51172u,  43100u,  63914u,  29888u,
     29763u,  61197u,  29443u,  55750u,  58596u,  16800u,  31102u,  15553u,  31649u,  51291u,
     32914u,  46648u,   2874u,  53590u,  53637u,   3908u,  58544u,  20239u,  56230u,  33115u,
     57434u,  48828u,  17731u,  48412u,   8952u,  39974u,   4542u,   5489u,  52074u,  43969u,
      4151u,  47778u,   1234u,  46389u,  45285u,   4510u,  12706u,  10210u,  62476u,  40359u,
      5890u,  58854u,  63554u,  41227u,   1466u,  23006u,  13347u,  11082u,   2185u,  25400u,
     46156u,  58895u,  64248u,  50065u,  53686u,  36811u,  40897u,   5170u,  32134u,  61845u,
     23780u,   9114u,  40937u,  45635u,  14752u,  23379u,  57543u,  22694u,  26546u,  42312u,
     23879u,  29525u,   3235u,  20053u,  48289u,  33613u,  33189u,  59230u,   5315u,  61917u,
      8732u,  18830u,  24714u,  63398u,  47024u,  33020u,   5688u,   1106u,  37908u,  53616u,
     45229u,  60725u,   8647u,  32859u,  25304u,  37153u,  35774u,  15325u,  54263u,  21259u,
     52598u,  22716u,  26875u,  43518u,  18697u,  21140u,   6297u,  34980u,  20278u,  57563u,
     59597u,   3664u,   9388u,  27715u,  11544u,
#else
     1619200496u,   767289150u,   847360606u,  3436261277u,  2075833113u,   958690292u,
     1853731489u,    50461944u,   993293357u,  1282118969u,  2749301546u,  3580011117u,
      415995098u,  2145183004u,  3984332404u,    47331933u,   545414375u,   245168718u,
     4263997113u,  2654026198u,   691356676u,  4149900813u,  1612000216u,   630602160u,
     1257503039u,  1518194861u,  2567067104u,  1709346590u,  1013496375u,  2950006291u,
     3935258569u,   317687734u,  1961819606u,  3658935058u,  4008396130u,   796546838u,
     2127770614u,   871340999u,  2360824291u,   928481915u,    92232588u,  2498086782u,
     3507346023u,  1130301986u,   292298343u,   323626153u,  4167606480u,  1207377402u,
      418004014u,  3908085619u,   737763321u,  1372221041u,   304574956u,   562863520u,
      275399126u,  3608093906u,  1123844967u,  1341409624u,  3378033676u,   474198774u,
     3482874817u,  2750451884u,  2981179739u,  1840310909u,  1227245972u,  1223940120u,
     3353594502u,  2824627452u,  4188679355u,  1958743125u,  1950555428u,  4010597695u,
     1929552563u,  3653615792u,  3840115019u,  1100986776u,  2038308113u,  1019262638u,
     2074135307u,  3361393141u,  2157028423u,  3057125953u,   188356918u,  3512104540u,
     3515168840u,   256100793u,  3836748398u,  1326406931u,  3685090637u,  2170196262u,
     3764020259u,  3200002477u,  1162029682u,  3172725208u,   586707870u,  2619748701u,
      297668226u,   359700203u,  3412742708u,  2881577805u,   272051693u,  3131205104u,
       80896266u,  3040152289u,  2967806338u,   295536856u,   832720476u,   669112634u,
     4094433914u,  2644982362u,   386022873u,  3857080917u,  4165062804u,  2701822975u,
       96065571u,  1507726455u,   874701658u,   726258924u,   143169650u,  1664616389u,
     3024849176u,  3859749508u,  4210537941u,  3281054650u,  3518356373u,  2412444071u,
     2680225997u,   338806415u,  2105944997u,  4053063846u,  1558443731u,   597318717u,
     2682863417u,  2990749167u,   966764168u,  1532153797u,  3771118674u,  1487299139u,
     1739728093u,  2772942139u,  1564957076u,  1934972375u,   211981740u,  1314219099u,
     3164642794u,  2202837283u,  2175067314u,  3881673128u,   348320113u,  4057814174u,
      572244531u,  1234021724u,  1619625940u,  4154845690u,  3081769110u,  2163967096u,
      372748842u,    72468672u,  2484321028u,  3513751713u,  2964104675u,  3979667795u,
      566667124u,  2153429096u,  1658353256u,  2434869914u,  2344473977u,  1004312901u,
     3556198731u,  1393205347u,  3447036200u,  1488691432u,  1761281214u,  2852000386u,
     1225309418u,  1385438747u,   412663613u,  2292445411u,  1328943020u,  3772428754u,
     3905721836u,   240117403u,   615275655u,  1816357900u,   756566226u,
#endif
};

/* -------------------------------------------------------------------------
 * Per cluster: the full-rate carrier increment, and where the cluster's lines
 * start.  s_ck_cluster_first has one extra entry so a cluster's line range is
 * [first[k], first[k+1]) with no count array.
 * ------------------------------------------------------------------------- */
static const avas_type_ty_ck_carph_t s_ck_car_step[AVAS_TYPE_TY_CK_CLUSTERS] = {
#if ((AVAS_TYPE_TY_CK_PHBITS_CAR) == 16)
       254u,    623u,    933u,   1073u,   1461u,   1706u,   2017u,   2256u,
      2700u,   2959u,   3972u,
#else
       16642488u,    40806243u,    61137562u,    70346831u,    95720880u,
      111804719u,   132215656u,   147823388u,   176979604u,   193946952u,
      260328347u,
#endif
};

static const uint16_t s_ck_cluster_first[AVAS_TYPE_TY_CK_CLUSTERS + 1] = {
       0u,   25u,   52u,   79u,   98u,  111u,  130u,  158u,  168u,  177u,  183u,  185u,
};

#endif /* !AVAS_CK_VOICE_TYPE_LB -- the Type_TY coefficient set */

#if ((AVAS_TYPE_TY_CK_ENVINTERP) == 1)
/* -------------------------------------------------------------------------
 * CORDIC constants for polar's (I,Q) -> (A,phi), which runs 11 times per rebuild.
 *
 * atan(2**-i) EXPRESSED AS A PHASE, not as an angle: the conversion accumulates
 * straight into the same units the carrier phase uses, so nothing in the firmware
 * ever holds radians and the wrap is again just the accumulator's overflow.  That
 * makes the table per-width, like the step tables.
 *
 * 12 iterations.  Each resolves about one bit of angle and the model's sweep put the
 * knee at 10 (42.84 dB against 42.87 at 12, i.e. flat) -- so 12 sits in the flat
 * region with two iterations of margin, and dropping to 10 is a measured lever worth
 * about 0.4 % of the block if flash or load ever needs it.  It is also where the
 * table stops saying anything at a 16-bit phase: atan(2**-13) is 1.3 phase units.
 *
 * KINV_Q15 is 1/K for the CORDIC's fixed vector growth K = 1.6467602.  The engine halves
 * the input first (K*32767 does not fit int16, and 16-bit x/y is what makes this
 * affordable), so the >> 14 that goes with this constant undoes both scalings at
 * once -- see avas_type_ty_ck_to_polar().
 * ------------------------------------------------------------------------- */
#define AVAS_TYPE_TY_CK_CORDIC_N           (12u)
#define AVAS_TYPE_TY_CK_CORDIC_KINV_Q15    (19898)
/* Half a turn at this width: the pre-rotation that puts the vector in the right
 * half plane, where a vectoring CORDIC converges. */
#define AVAS_TYPE_TY_CK_CORDIC_HALF       ((avas_type_ty_ck_carph_t)1u << ((AVAS_TYPE_TY_CK_PHBITS_CAR) - 1))

static const avas_type_ty_ck_carph_t s_ck_cordic_atan[AVAS_TYPE_TY_CK_CORDIC_N] = {
#if ((AVAS_TYPE_TY_CK_PHBITS_CAR) == 16)
      8192u,   4836u,   2555u,   1297u,    651u,    326u,
       163u,     81u,     41u,     20u,     10u,      5u,
#else
      536870912u,   316933406u,   167458907u,    85004756u,    42667331u,
       21354465u,    10679838u,     5340245u,     2670163u,     1335087u,
         667544u,      333772u,
#endif
};
#endif /* ENVINTERP == 1 */

#endif /* AVAS_TYPE_TY_CK_TABLES_H */
