/* =========================================================================
 * Type_LB AVAS L3 line model -- FIXED-POINT coefficient set for dsPIC33CK
 * GENERATED by tools/gen_avas_type_lb_ck_tables.py -- DO NOT EDIT
 *
 * Source of the coefficients:
 *     tools/L3_params_type_lb.txt  (all 264 detected lines of the flat-pitch
 *     window -- L3 is the UNTRUNCATED tone model; L4/L5/L8 take the top 64)
 * Source of every derived integer below:
 *     tools/avas_type_ty_fixed_model.py  (imported by the generator, so the model that
 *     measured this design and the firmware that runs it share one set of numbers by
 *     construction).  That module is the ENGINE's model, driven with this voice's
 *     table -- see tools/avas_type_lb_fixed_model.py.
 *
 * WHAT IS NOT IN THIS FILE, and that is the point: the sine table, the CORDIC
 * constants, the gate's one-pole, the phase/envelope typedefs and every build-time
 * knob live in avas_type_ty_ck_tables.h and are SHARED by both voices.  L3's tone part
 * is the same equation the Type_TY voice computes (design section 2), so a voice is
 * five arrays, two counts and one level -- nothing more.
 *
 * fs is BAKED IN: bb_step and car_step are both scaled by it.  Regenerate for
 * another rate rather than converting.
 * ========================================================================= */

#ifndef AVAS_TYPE_LB_CK_TABLES_H
#define AVAS_TYPE_LB_CK_TABLES_H

#include <stdint.h>

/* The shared half of the engine's tables, and the typedefs the arrays below are
 * declared with.  Including it here rather than relying on include order means this
 * header is self-sufficient. */
#include "avas_type_ty_ck_tables.h"

#define AVAS_TYPE_LB_CK_TABLE_FS_HZ   (48000u)
#define AVAS_TYPE_LB_CK_MODEL_LABEL   "L3"    /* lines + 1.5 dB noise movement; the
                                             * noise bank is a separate stage */
#define AVAS_TYPE_LB_CK_LINES         (264u)
#define AVAS_TYPE_LB_CK_CLUSTERS      (7u)
#define AVAS_TYPE_LB_CK_MAX_SPAN_HZ   (100)

#if defined(AVAS_TYPE_TY_CK_APP_FS_HZ) && \
    ((AVAS_TYPE_TY_CK_APP_FS_HZ) != (AVAS_TYPE_LB_CK_TABLE_FS_HZ))
#error "avas_type_lb_ck: this coefficient set's fs does not match the app's -- regenerate it.  A silent mismatch is a pitch error, not a failure."
#endif

/* -------------------------------------------------------------------------
 * THE CLUSTER DECOMPOSITION, at MAX_SPAN_HZ = 100.
 *
 * Greedy contiguous runs of ascending frequency no wider than the span, carrier at
 * the amplitude-weighted centroid so the smallest baseband offset lands on the
 * strongest lines.  Only these 7 carriers run at fs; each cluster's complex
 * envelope is rebuilt every AVAS_TYPE_TY_CK_DEC samples and interpolated in between.
 *
 *   #   carrier Hz    lines   span Hz   max |f-fc|   energy %
 *   0       66.82       50     79.74       47.67      85.31
 *   1      197.34       73     89.07       60.66       9.61
 *   2      319.86       64     96.73       51.64       4.35
 *   3      454.73       24     61.73       43.55       0.19
 *   4      590.23        2      1.53        0.82       0.01
 *   5      987.73       50     78.92       52.88       0.53
 *   6     1121.83        1      0.00        0.00       0.00
 *
 * WHY 100 Hz AND NOT WIDER, measured four ways in design section 12: the span sets
 * the interpolation error (max |f-fc| above), the amplitude resolution (A_SCALE is
 * 32767 / the WIDEST cluster's amplitude sum, so every line in the table pays for
 * the fattest one), the output headroom (the same sum is the output gain's
 * denominator -- above 100 Hz the gain exceeds unity and the engine needs a shift
 * and a clamp) and the load (11.88 us per extra carrier per block, MEASURED on the
 * Type_TY voice).  All four point the same way here, which is why the doc's original
 * "200 or 150" is not the answer.
 *
 * REALISED FREQUENCY ERROR at the two phase widths, computed by the model:
 *     32/32   carrier <= 0.000004 Hz   baseband <= 0.000000 Hz
 *     16/16   carrier <= 0.321147 Hz   baseband <= 0.011443 Hz   (<= 4.35 cents)
 * Cents is the readable form for this voice: its carriers sit at 67-1122 Hz where
 * the Type_TY's sit at 234-2169, so the same absolute resolution error is worth
 * several times more of a pitch shift.  What that is worth is a listening question
 * (phase 5) and the numbers are here so it is not answered by a comment.
 * ------------------------------------------------------------------------- */

/* -------------------------------------------------------------------------
 * THE OUTPUT LEVEL, and the one place this voice needs arithmetic the Type_TY voice
 * does not.
 *
 * The gain maps the accumulated y -- in the scaled units the amplitude table uses --
 * to Q15, reproducing the reference WAV's level: the measured 60 s peak of the full
 * 264-line sum (0.631084) normalised to 0.9 of full scale.
 *
 * Q15 CANNOT ALWAYS HOLD IT.  A_SCALE is set by the worst CLUSTER's amplitude sum
 * while the numerator is the peak the WHOLE sum reaches, and those are independent:
 * Type_TY's 11 narrow clusters make them nearly equal (ratio 1.026, gain 0.877),
 * while a few fat Type_LB clusters do not.  So the gain is carried as a Q15
 * mantissa plus a left SHIFT -- an octave is free on this core, only the mantissa
 * costs a multiply -- and AVAS_TYPE_LB_CK_NORM_SHIFT is 0 whenever the gain fits, in
 * which case the engine's output path is textually the shift it has always done.
 *
 * At this span the shift is 0 and the linear gain is 0.9329.
 * ------------------------------------------------------------------------- */
#define AVAS_TYPE_LB_CK_NORM_GAIN_Q15 (30569)
#define AVAS_TYPE_LB_CK_NORM_SHIFT    (0)

/* -------------------------------------------------------------------------
 * Per line, frequency ascending.  Each cluster is a contiguous run, which is why no
 * per-line cluster index exists.  Same three arrays, same meanings and the same
 * types as the Type_TY set -- these are literally the other instance of
 * avas_line_ck_set_t.
 *
 *   amp_q15  amplitude, scaled so the strongest cluster's amplitude SUM fills Q15
 *            (50090.6 here; the weakest line lands on 77 counts).
 *   bb_step  (f - fc)*DEC/fs as a phase increment, signed.
 *   bb_pha0  the measured cos phase, as a whole cycle of 2^PHBITS_BB.
 *
 * Both step tables are rounded FROM THE FREQUENCY at their own width.
 * ------------------------------------------------------------------------- */
static const int16_t s_ck_type_lb_amp_q15[AVAS_TYPE_LB_CK_LINES] = {
        81,    150,    128,    171,    238,    326,    366,    782,    937,   2064,
     13002,   2032,   1625,   1152,    560,    467,    299,    130,    141,    124,
       118,    119,     96,     94,    123,     79,    102,    129,    283,    390,
       115,     77,     88,     88,    197,    163,    497,    340,   1489,    364,
       306,    161,    649,   1205,    203,    145,    110,    108,     78,     77,
       140,    139,    294,     94,     91,    138,    126,     82,    103,    120,
       126,    212,    164,    146,    337,    201,    219,    147,    134,    155,
       228,    120,    136,    148,    155,    452,   1343,    998,    260,    252,
       162,    856,    684,    149,    190,    121,     78,     77,     88,    167,
       144,    165,    137,    197,    366,    387,    328,    194,    183,    457,
       333,    785,    336,    702,    987,   1894,    923,   1434,   1335,   1316,
      1498,    444,    230,    492,    343,    142,    114,    233,    126,    145,
       172,     81,     78,    148,     90,    119,     87,     87,    104,    114,
       135,     83,     81,    137,    164,    325,    169,    317,    345,    395,
       369,    259,    315,    166,    189,    251,    110,    108,    168,    120,
        83,    137,     89,     96,     78,    121,     95,     93,    126,    126,
       161,    318,    285,    311,    312,    620,    887,    739,   1464,   1801,
       682,    352,    294,    184,    147,    104,    111,     93,     81,     80,
        82,     95,     89,     82,     79,     86,    172,     80,     92,    120,
       120,    342,    221,    193,    126,    114,    105,     87,     79,     78,
        82,    106,     82,    122,     82,    112,     90,     91,     92,     88,
       132,     92,     79,     99,     82,    105,     83,    129,     85,     79,
        87,     90,     96,     99,    150,    191,    162,    150,    169,    232,
       181,    137,    166,    159,    165,    166,    222,    252,    138,    142,
       185,    166,    166,    202,    167,    152,    296,    156,    218,    173,
       173,    188,    134,    116,    124,    141,    138,     94,    117,     89,
        90,     94,     78,     89,
};

static const avas_type_ty_ck_bbstep_t s_ck_type_lb_bb_step[AVAS_TYPE_LB_CK_LINES] = {
#if ((AVAS_TYPE_TY_CK_PHBITS_BB) == 16)
      -1401,    -743,    -702,    -679,    -649,    -617,    -583,    -560,    -548,    -535,
       -520,    -506,    -495,    -481,    -454,    -439,    -414,    -386,    -357,    -330,
       -302,    -263,     331,     431,     455,     554,     608,     637,     673,     687,
        701,     716,    1764,    1777,    1820,    1842,    1856,    1869,    1883,    1911,
       1934,    1949,    1963,    1989,    2013,    2028,    2044,    2055,    2069,    2083,
      -2650,   -2625,   -2608,   -2569,   -2518,   -2502,   -2479,   -2465,   -2437,   -2384,
      -2344,   -2319,   -2290,   -2275,   -2238,   -2203,   -2191,   -2153,   -2050,   -2020,
      -2008,   -1524,   -1503,   -1477,   -1463,   -1440,   -1420,   -1405,   -1356,   -1340,
      -1317,   -1276,   -1259,   -1229,   -1214,   -1194,   -1028,    -205,     531,     687,
        702,     714,     728,     752,     766,     780,     793,     809,     833,     847,
        859,     874,     891,     926,     939,     954,     965,     979,     993,    1006,
       1020,    1045,    1060,    1074,    1097,    1128,    1146,    1161,    1185,    1200,
       1217,    1230,    1241,   -1970,   -1956,   -1942,   -1470,   -1389,   -1351,   -1339,
      -1323,   -1298,   -1283,   -1267,   -1217,   -1203,   -1189,   -1164,   -1150,   -1123,
      -1110,   -1074,   -1058,   -1044,   -1030,   -1017,   -1002,    -989,    -951,    -938,
       -911,    -897,     111,     123,     157,     178,     236,     256,     286,     298,
        322,     348,     361,     392,     400,     418,     457,     471,     485,     498,
        538,     566,     577,     591,     604,     619,     630,     662,    1167,    1960,
       1976,    1989,    2028,    2061,    2082,    2238,    2256,    -794,    -766,    -743,
       -703,    -635,    -621,    -609,    -597,    -557,    -526,    -489,    -481,    -390,
        683,     697,     709,     722,     775,     816,     828,     884,     908,    1876,
       1903,     -31,      36,   -2310,   -2161,   -2015,   -1947,   -1934,   -1895,   -1786,
      -1559,   -1037,    -498,    -458,    -392,    -244,    -204,    -124,    -110,     -84,
        -70,     -57,     -43,      -2,      37,      65,      77,      92,     102,     118,
        144,     157,     171,     212,     241,     250,     266,     279,     306,     387,
        454,     521,     601,     777,     923,     963,     977,    1004,    1017,    1044,
       1099,    1110,    1138,       0,
#else
       -91818909,    -48699502,    -45975669,    -44480298,    -42519027,    -40467494,
       -38202330,    -36709768,    -35889082,    -35046815,    -34056103,    -33163397,
       -32420522,    -31496362,    -29742242,    -28793756,    -27158758,    -25322365,
       -23365041,    -21600907,    -19796430,    -17232284,     21724303,     28253389,
        29829619,     36326633,     39841154,     41776761,     44135127,     45030102,
        45941748,     46917547,    115636341,    116429607,    119259862,    120742537,
       121655846,    122479083,    123377346,    125246742,    126773683,    127740648,
       128676158,    130371930,    131917364,    132928185,    133940908,    134702586,
       135600274,    136502850,   -173676140,   -172029055,   -170913224,   -168353703,
      -165030771,   -163961525,   -162465283,   -161528498,   -159722313,   -156245353,
      -153613987,   -151987325,   -150089348,   -149103571,   -146699765,   -144380568,
      -143602528,   -141116017,   -134329608,   -132365563,   -131619085,    -99891343,
       -98491729,    -96798810,    -95861128,    -94376606,    -93048395,    -92065233,
       -88852871,    -87821104,    -86295391,    -83596955,    -82524582,    -80527969,
       -79582860,    -78218993,    -67355147,    -13403582,     34810174,     45048289,
        46006136,     46771107,     47730085,     49305233,     50228654,     51134829,
        51976054,     52992634,     54617264,     55499903,     56300515,     57257373,
        58360079,     60715738,     61505929,     62519209,     63245972,     64141864,
        65075447,     65909137,     66836465,     68513340,     69487561,     70373896,
        71917433,     73944341,     75129857,     76093409,     77629305,     78646693,
        79754037,     80577943,     81346680,   -129120470,   -128158391,   -127280578,
       -96339190,    -91054483,    -88561370,    -87726329,    -86686565,    -85078740,
       -84100034,    -83030601,    -79749698,    -78840139,    -77894442,    -76251289,
       -75382473,    -73600252,    -72733417,    -70373570,    -69316654,    -68410667,
       -67512257,    -66635266,    -65652122,    -64841874,    -62330728,    -61445789,
       -59683306,    -58778111,      7303301,      8072038,     10280782,     11637141,
        15495389,     16745922,     18772178,     19543257,     21082460,     22810223,
        23666908,     25711254,     26200595,     27426813,     29973509,     30852696,
        31794418,     32639256,     35253829,     37081663,     37803931,     38756523,
        39610989,     40582024,     41300105,     43354087,     76491323,    128446504,
       129472628,    130325444,    132888455,    135093379,    136437702,    146640572,
       147856081,    -52057373,    -50173092,    -48718990,    -46043424,    -41589155,
       -40712187,    -39928660,    -39115336,    -36525955,    -34452184,    -32075735,
       -31512093,    -25586261,     44755819,     45685425,     46437138,     47315230,
        50776610,     53488876,     54275074,     57923330,     59476294,    122931156,
       124708552,     -2028034,      2353440,   -151400697,   -141653492,   -132072114,
      -127610589,   -126765798,   -124184795,   -117058304,   -102181290,    -67937671,
       -32664529,    -30039546,    -25704744,    -15973568,    -13389684,     -8141657,
        -7181289,     -5478106,     -4575784,     -3739452,     -2811081,      -151568,
         2404219,      4231511,      5018728,      5998740,      6701958,      7743108,
         9442370,     10275152,     11186320,     13884316,     15799557,     16375600,
        17401708,     18268148,     20065736,     25384210,     29747363,     34135735,
        39398372,     50947228,     60473239,     63124707,     64024270,     65793503,
        66624671,     68417118,     71992641,     72729712,     74567233,            0,
#endif
};

static const avas_type_ty_ck_bbph_t s_ck_type_lb_bb_pha0[AVAS_TYPE_LB_CK_LINES] = {
#if ((AVAS_TYPE_TY_CK_PHBITS_BB) == 16)
     18951u,  45732u,  29246u,  55846u,  21040u,  48334u,  59041u,  60678u,  11240u,  16195u,
     52793u,  15210u,  60082u,  27744u,  27276u,   9775u,  33777u,  22918u,  28761u,  16344u,
      9861u,   7794u,   3350u,  14052u,  40899u,  13476u,  41123u,  65110u,   5174u,  34333u,
     56133u,  21489u,  45475u,  45965u,  53474u,  35412u,   4984u,  35961u,  38583u,  42360u,
     27439u,  35023u,  29379u,  18985u,  52972u,  21437u,  62327u,  60365u,  30005u,  29558u,
     56053u,  56365u,  58240u,  19325u,  13832u,  51666u,  43401u,   3372u,  22292u,  30821u,
     29812u,   8740u,  47112u,  35697u,  42378u,  57511u,  63800u,  24508u,   2755u,  14592u,
     49755u,  11139u,  24287u,  33378u,  38931u,   6355u,  40980u,  15840u,  29548u,  27798u,
     55479u,  12897u,  59336u,  54916u,  12046u,  37940u,   1893u,  25665u,  64659u,  62771u,
     50244u,  61570u,  45544u,  13686u,   4657u,  10039u,  61948u,  15275u,  10358u,  27626u,
     64504u,  11083u,  65187u,    931u,  33559u,  28015u,  28448u,   2782u,  61877u,  60584u,
      8171u,  29346u,  34885u,  37982u,   7481u,  61187u,  41085u,  41984u,  54803u,   2938u,
     20542u,  18281u,  14828u,  11154u,  30852u,  54815u,  13319u,  14151u,  30650u,  39271u,
     54559u,  11031u,   8258u,  56403u,   7137u,   3633u,  10286u,   2259u,  10035u,  21880u,
     16049u,  50237u,   1804u,   8577u,  20323u,  45903u,  36658u,  35777u,   9975u,  45377u,
     12057u,  56715u,  17660u,  24521u,   7016u,  46386u,  24010u,  21631u,  48572u,  47869u,
      5237u,  64951u,  54140u,  61908u,  62240u,  57344u,  23873u,   7912u,   3706u,  22404u,
     64933u,   5154u,  54405u,  11680u,  56587u,  25442u,  30486u,  14092u,  10412u,  26598u,
     28776u,  41944u,  37162u,  31533u,  28778u,  43574u,  41982u,  55540u,   2521u,  25609u,
     26704u,  53873u,  12728u,   1449u,  26270u,  16582u,   7801u,  56208u,  48259u,  43634u,
     41160u,  64886u,  41845u,  12038u,  40928u,   1216u,  47134u,  47167u,  47006u,  42029u,
     13469u,  19998u,  10235u,  56748u,  37280u,  57493u,  36406u,  10293u,  35143u,  24850u,
     33431u,  34420u,   9651u,   8854u,  40589u,  47005u,  30667u,  21312u,  31527u,  55934u,
     33222u,   6716u,  23369u,  18072u,  19071u,  18413u,  44389u,  54776u,  65498u,   1198u,
     24143u,  14675u,  14529u,  32257u,  13056u,   4297u,  64378u,   6613u,  36940u,  16551u,
     17292u,  26171u,  63008u,  64074u,  21459u,  37913u,  36895u,   5629u,  25782u,   3242u,
     10688u,  14932u,   1135u,  32134u,
#else
     1241990370u,  2997088864u,  1916657791u,  3659940765u,  1378878329u,  3167645551u,
     3869293026u,  3976615822u,   736617422u,  1061359908u,  3459834262u,   996786201u,
     3937501358u,  1818221421u,  1787583376u,   640617138u,  2213577435u,  1501960110u,
     1884868462u,  1071139423u,   646243783u,   510770658u,   219544443u,   920902639u,
     2680357815u,   883165191u,  2695021353u,  4267050085u,   339050626u,  2250018177u,
     3678755761u,  1408312920u,  2980257352u,  3012329610u,  3504476058u,  2320736756u,
      326647888u,  2356725926u,  2528602959u,  2776088195u,  1798262649u,  2295243404u,
     1925359592u,  1244175780u,  3471543107u,  1404912425u,  4084656175u,  3956108170u,
     1966404358u,  1937105291u,  3673478772u,  3693905437u,  3816837653u,  1266477034u,
      906474822u,  3385992572u,  2844319073u,   220975219u,  1460909400u,  2019900164u,
     1953730716u,   572767600u,  3087550440u,  2339460760u,  2777287202u,  3769029657u,
     4181225405u,  1606174240u,   180566590u,   956273345u,  3260737082u,   729976175u,
     1591678600u,  2187470205u,  2551383410u,   416480866u,  2685633402u,  1038085824u,
     1936447270u,  1821759578u,  3635853247u,   845238665u,  3888630420u,  3598984530u,
      789454841u,  2486423843u,   124055036u,  1681982832u,  4237470134u,  4113737653u,
     3292772248u,  4035036511u,  2984793019u,   896903570u,   305190529u,   657901476u,
     4059842477u,  1001052912u,   678845820u,  1810497389u,  4227313920u,   726367174u,
     4272126868u,    61030619u,  2199296360u,  1836018341u,  1864345393u,   182289102u,
     4055164506u,  3970429284u,   535497579u,  1923223785u,  2286246988u,  2489195692u,
      490280881u,  4009937588u,  2692540874u,  2751495484u,  3591539510u,   192550522u,
     1346271081u,  1198066934u,   971773231u,   730965102u,  2021898617u,  3592353853u,
      872902729u,   927428487u,  2008693905u,  2573685008u,  3575570006u,   722950703u,
      541223539u,  3696455318u,   467755970u,   238121477u,   674123376u,   148015203u,
      657679988u,  1433953471u,  1051814721u,  3292312109u,   118234169u,   562099535u,
     1331869117u,  3008274870u,  2402414833u,  2344690269u,   653730867u,  2973850930u,
      790169643u,  3716865605u,  1157344378u,  1606985054u,   459819976u,  3039958814u,
     1573545439u,  1417620648u,  3183228983u,  3137149625u,   343193778u,  4256612838u,
     3548115015u,  4057211324u,  4078937575u,  3758107205u,  1564550582u,   518503911u,
      242872144u,  1468268895u,  4255447248u,   337799027u,  3565463187u,   765476023u,
     3708457038u,  1667354386u,  1997912827u,   923525579u,   682334564u,  1743115277u,
     1885853960u,  2748833600u,  2435463107u,  2066557709u,  1886004405u,  2855653992u,
     2751326962u,  3639866816u,   165241769u,  1678314775u,  1750061178u,  3530595485u,
      834166246u,    94951507u,  1721634709u,  1086724877u,   511247265u,  3683635531u,
     3162695306u,  2859628712u,  2697485867u,  4252393312u,  2742353548u,   788923644u,
     2682267510u,    79713188u,  3089000835u,  3091144161u,  3080617793u,  2754409799u,
      882686168u,  1310611125u,   670788896u,  3719044587u,  2443193356u,  3767886784u,
     2385879253u,   674558642u,  2303163119u,  1628595897u,  2190901333u,  2255772125u,
      632495923u,   580274816u,  2660010592u,  3080529018u,  2009810147u,  1396723885u,
     2066147000u,  3665669066u,  2177237052u,   440147737u,  1531537825u,  1184384266u,
     1249841633u,  1206686815u,  2909048770u,  3589780455u,  4292459723u,    78543251u,
     1582226650u,   961768711u,   952147116u,  2114000443u,   855653414u,   281599973u,
     4219091093u,   433366926u,  2420868103u,  1084665484u,  1133241770u,  1715150246u,
     4129310741u,  4199183883u,  1406306996u,  2484672770u,  2417935924u,   368899697u,
     1689673548u,   212483977u,   700417466u,   978568815u,    74374336u,  2105909759u,
#endif
};

/* Per cluster: the full-rate carrier increment, and where the cluster's lines start.
 * s_ck_type_lb_cluster_first has one extra entry so a cluster's line range is
 * [first[k], first[k+1]) with no count array. */
static const avas_type_ty_ck_carph_t s_ck_type_lb_car_step[AVAS_TYPE_LB_CK_CLUSTERS] = {
#if ((AVAS_TYPE_TY_CK_PHBITS_CAR) == 16)
        91u,    269u,    437u,    621u,    806u,   1349u,   1532u,
#else
        5978792u,    17657920u,    28620881u,    40688942u,    52812994u,
       88380735u,   100379606u,
#endif
};

static const uint16_t s_ck_type_lb_cluster_first[AVAS_TYPE_LB_CK_CLUSTERS + 1] = {
       0u,   50u,  123u,  187u,  211u,  213u,  263u,  264u,
};

#endif /* AVAS_TYPE_LB_CK_TABLES_H */
