/*
 * avas_type_lb_ck_noise_tables.h -- the L3 voice's NOISE half, GENERATED.
 *
 * GENERATED by tools/gen_avas_type_lb_ck_noise.py -- DO NOT EDIT.  Every integer here is
 * measured by tools/avas_type_lb_noise_fixed.py (design section 14) and re-measured on
 * the exact integer arithmetic avas_noise_bank_ck.c runs.
 *
 * WHAT THIS IS: one white source, tilted once by a single Q15 one-pole, feeding 12
 * Chamberlin state-variable bandpasses whose outputs are summed with fitted gains.
 * NOT a bank of direct-form biquads: at the lowest band's 24 Hz centre a Q14 `a1`
 * quantises the pole ANGLE by 100%, i.e. the centre frequency becomes arbitrary.  The
 * SVF tunes on F = 2 sin(pi f0 / fs), which at that centre is 0.3% off.
 *
 * BANDS, and why there are 12 and not 13.  The fit put band 11 (1189-1724 Hz) at
 * gain Q15 = 0 -- band 10 is at full scale next door and its skirt already covers
 * band 11's target.  A zero-gain band cannot contribute to the output but still costs
 * three multiplies a sample, so it is not built.  The generator PROVES the removal is
 * bit-identical before emitting this file.
 *
 *    0      20-    29 Hz   F   103   gain 11009   err -1.14 dB
 *    1      29-    42 Hz   F   150   gain  9653   err +1.25 dB
 *    2      42-    61 Hz   F   217   gain 13215   err +0.19 dB
 *    3      61-    88 Hz   F   315   gain 14463   err -0.94 dB
 *    4      88-   128 Hz   F   456   gain 10931   err +0.92 dB
 *    5     128-   186 Hz   F   661   gain  4917   err +1.16 dB
 *    6     186-   269 Hz   F   959   gain 15385   err +0.34 dB
 *    7     269-   390 Hz   F  1390   gain 16853   err +1.12 dB
 *    8     390-   566 Hz   F  2015   gain 16512   err -0.08 dB
 *    9     566-   820 Hz   F  2921   gain  8094   err -0.11 dB
 *   10     820-  1189 Hz   F  4232   gain 32767   err -1.45 dB
 *   12    1724-  2499 Hz   F  8874   gain  3253   err -0.00 dB
 *
 * MEASURED over 2 s of this arithmetic: band-level shape error mean +0.09 dB,
 * worst -1.45 dB, rms 0.85 dB; peak |y| 18503 counts, rms 4584 counts.
 *
 * THE LEVEL IS NOT A TUNING KNOB.  NG[b] and the tone's AMP[] are both in the
 * reference sound's units, so tone + noise is a sum with nothing free in it: the bank's
 * counts are converted to the engine's A_SCALE units by AVAS_TYPE_LB_CK_NOISE_GAIN_Q15
 * >> AVAS_TYPE_LB_CK_NOISE_GAIN_SHIFT, measured as k * A_SCALE = 5.779472e-06 * 50090.6.
 * The realised noise/tone ratio is -18.01 dB against the table's -17.85 dB.
 */
#ifndef AVAS_TYPE_LB_CK_NOISE_TABLES_H
#define AVAS_TYPE_LB_CK_NOISE_TABLES_H

#include <stdint.h>

#define AVAS_TYPE_LB_CK_NOISE_BANDS           (12u)

/* 1/Q in Q15, SHARED by every band: the bands are geometric with a common ratio, so
 * they have a common Q -- which is what makes the -3 dB edges land on the band edges. */
#define AVAS_TYPE_LB_CK_NOISE_Q1_Q15          (12239)

/* The source tilt: ONE Q15 one-pole at 348 Hz, `y += (a*(x-y)) >> 15`.  It exists
 * because a 2nd-order skirt falls at 6 dB/octave and this target falls at
 * 12.4 dB/octave, so no vector of gains can fix it -- fitting white-driven bands left
 * five gains at zero and the composite was still +27 dB too loud at 9 kHz.  Tilting the
 * SOURCE costs 3-4 instructions ONCE for the whole bank. */
#define AVAS_TYPE_LB_CK_NOISE_TILT_A_Q15      (1493)

/* Counts -> the engine's A_SCALE units.  See the level note above. */
#define AVAS_TYPE_LB_CK_NOISE_GAIN_Q15        (9486)
#define AVAS_TYPE_LB_CK_NOISE_GAIN_SHIFT      (15)

/* The gust: L3 is `tone + noise(mod_db=1.5)`, and the 1.5 dB is a slow per-band random
 * walk at 1.2 Hz -- it moves energy around in time without changing any band's
 * long-term rms.  Updated once per DEC samples, so it costs NOTHING per sample: the
 * modulated gain is folded into the same coefficient the bank already multiplies by.
 *
 * The model drives the walk with a Gaussian and converts dB to linear with pow(); the
 * ISR can afford neither, so this is a uniform drive and a first-order 10^(x/20).  The
 * sd that comes out is MEASURED (1.56 dB against the model's 1.5 dB) rather than
 * assumed equal. */
#define AVAS_TYPE_LB_CK_NOISE_GUST_A_Q15      (165)
/* NOT an int16: ~6.0 in Q15.  The clamp is what keeps `K * walk` inside int32. */
#define AVAS_TYPE_LB_CK_NOISE_GUST_K_Q15      (195091L)
#define AVAS_TYPE_LB_CK_NOISE_GUST_WALK_LIM   (3802)

/* The white source is the xorshift32 sonora's Type_LB uses, from the same seed, so
 * the two boards' noise is comparable rather than merely similar. */
#define AVAS_TYPE_LB_CK_NOISE_SEED            (0x1234567uL)
#define AVAS_TYPE_LB_CK_NOISE_GUST_SEED       (0xC0FFEEuL)

/* F = 2 sin(pi f0 / fs) in Q15, one per band. */
static const int16_t s_ck_type_lb_noise_f_q15[AVAS_TYPE_LB_CK_NOISE_BANDS] = {
       103,    150,    217,    315,    456,    661,    959,   1390,
      2015,   2921,   4232,   8874,
};

/* The fitted gains in Q15, normalised so the loudest band is full scale.  Fitted on the
 * COHERENT sum |sum_b g_b H_b(f)|, not a power sum, because one shared white source
 * means overlapping skirts add with their phases. */
static const int16_t s_ck_type_lb_noise_g_q15[AVAS_TYPE_LB_CK_NOISE_BANDS] = {
     11009,   9653,  13215,  14463,  10931,   4917,  15385,  16853,
     16512,   8094,  32767,   3253,
};

#endif /* AVAS_TYPE_LB_CK_NOISE_TABLES_H */
