/* =========================================================================
 * dB -> Q12 mantissa table for the CK audio chain's PRE_GAIN / POST_GAIN --
 * GENERATED by tools/gen_gain_db_tables.py, DO NOT EDIT
 *
 * Grid: -24.0 dB to +24.0 dB in 0.5 dB steps (97 entries, 194 bytes of flash).
 * Worst realisation error over the whole grid: 0.014805 dB (at -24.0 dB, where the
 * mantissa is smallest); 0.002120 dB at unity.  The grid is 0.5 dB, so this is
 * three decimal orders below anything the knob can express.
 *
 * ONE mantissa per entry, consumed by gain_db.h's fixed-shift scale:
 *     t = x * m / 2^16      (two native 16x16 multiplies)
 *     y = t << 4            (saturating -- a boost CAN overflow)
 * so 0.0 dB is mantissa 0x1000 = 2^12 and reproduces x apart from its low 4
 * bits, which are pad and not audio (24-bit word left-justified in a 32-bit
 * slot) -- and the firmware skips the stage entirely at unity anyway.
 *
 * The shift is a CONSTANT on purpose: as a run-time field it cost seven
 * instructions a sample and spilled the clamp bounds.  See the generator's
 * header comment.
 * ========================================================================= */

#ifndef GAIN_DB_TABLES_H
#define GAIN_DB_TABLES_H

#include <stdint.h>

/* The grid, in half-decibels, inclusive.  Index 0 is GAIN_DB_HALF_MIN. */
#define GAIN_DB_HALF_MIN   (-48)      /* -24.0 dB */
#define GAIN_DB_HALF_MAX   (48)      /* +24.0 dB */
#define GAIN_DB_ENTRIES    (97)

/* The FIXED output shift, and the mantissa that means unity.  Both are used in
 * arithmetic and in the clamp bounds, so they are one definition, here. */
#define GAIN_DB_SHIFT      (4)
#define GAIN_DB_MANT_ONE   (0x1000u)   /* 2^12 -- exactly 0.0 dB */

/* Half-decibels -> table index, valid for GAIN_DB_HALF_MIN..GAIN_DB_HALF_MAX.
 * A constant expression, so the compile-time default costs no code at all. */
#define GAIN_DB_INDEX_OF_HALF(h)  ((h) - (GAIN_DB_HALF_MIN))

/* Tenths of a dB -> half-decibels, as a CONSTANT expression for the config
 * default.  Requires a multiple of 5 (app_config.h enforces it with an
 * #error); the run-time path snaps instead, see gain_db_from_x10(). */
#define GAIN_DB_HALF_OF_X10(x10)  ((x10) / 5)

/* The gain, as the multiplier the hot path uses: Q12, unity 0x1000. */
static const uint16_t gain_db_mant[GAIN_DB_ENTRIES] = {
    0x0102u,   /*  -24.0 dB  ->   0.06299 x   (realised -24.014805 dB) */
    0x0112u,   /*  -23.5 dB  ->   0.06689 x   (realised -23.492188 dB) */
    0x0122u,   /*  -23.0 dB  ->   0.07080 x   (realised -22.999239 dB) */
    0x0133u,   /*  -22.5 dB  ->   0.07495 x   (realised -22.504431 dB) */
    0x0145u,   /*  -22.0 dB  ->   0.07935 x   (realised -22.009532 dB) */
    0x0159u,   /*  -21.5 dB  ->   0.08423 x   (realised -21.490817 dB) */
    0x016Du,   /*  -21.0 dB  ->   0.08911 x   (realised -21.001342 dB) */
    0x0183u,   /*  -20.5 dB  ->   0.09448 x   (realised -20.492980 dB) */
    0x019Au,   /*  -20.0 dB  ->   0.10010 x   (realised -19.991522 dB) */
    0x01B2u,   /*  -19.5 dB  ->   0.10596 x   (realised -19.497404 dB) */
    0x01CCu,   /*  -19.0 dB  ->   0.11230 x   (realised -18.992042 dB) */
    0x01E7u,   /*  -18.5 dB  ->   0.11890 x   (realised -18.496620 dB) */
    0x0204u,   /*  -18.0 dB  ->   0.12598 x   (realised -17.994205 dB) */
    0x0222u,   /*  -17.5 dB  ->   0.13330 x   (realised -17.503346 dB) */
    0x0243u,   /*  -17.0 dB  ->   0.14136 x   (realised -16.993628 dB) */
    0x0265u,   /*  -16.5 dB  ->   0.14966 x   (realised -16.497989 dB) */
    0x0289u,   /*  -16.0 dB  ->   0.15845 x   (realised -16.002305 dB) */
    0x02B0u,   /*  -15.5 dB  ->   0.16797 x   (realised -15.495430 dB) */
    0x02D8u,   /*  -15.0 dB  ->   0.17773 x   (realised -15.004571 dB) */
    0x0304u,   /*  -14.5 dB  ->   0.18848 x   (realised -14.494853 dB) */
    0x0331u,   /*  -14.0 dB  ->   0.19946 x   (realised -14.002758 dB) */
    0x0362u,   /*  -13.5 dB  ->   0.21143 x   (realised -13.496841 dB) */
    0x0395u,   /*  -13.0 dB  ->   0.22388 x   (realised -12.999812 dB) */
    0x03CBu,   /*  -12.5 dB  ->   0.23706 x   (realised -12.502814 dB) */
    0x0405u,   /*  -12.0 dB  ->   0.25122 x   (realised -11.998891 dB) */
    0x0442u,   /*  -11.5 dB  ->   0.26611 x   (realised -11.498669 dB) */
    0x0482u,   /*  -11.0 dB  ->   0.28174 x   (realised -11.003083 dB) */
    0x04C7u,   /*  -10.5 dB  ->   0.29858 x   (realised -10.498670 dB) */
    0x050Fu,   /*  -10.0 dB  ->   0.31616 x   (realised -10.001804 dB) */
    0x055Cu,   /*   -9.5 dB  ->   0.33496 x   (realised -9.500117 dB) */
    0x05ADu,   /*   -9.0 dB  ->   0.35474 x   (realised -9.001887 dB) */
    0x0603u,   /*   -8.5 dB  ->   0.37573 x   (realised -8.502427 dB) */
    0x065Fu,   /*   -8.0 dB  ->   0.39819 x   (realised -7.998120 dB) */
    0x06BFu,   /*   -7.5 dB  ->   0.42163 x   (realised -7.501352 dB) */
    0x0726u,   /*   -7.0 dB  ->   0.44678 x   (realised -6.998177 dB) */
    0x0792u,   /*   -6.5 dB  ->   0.47314 x   (realised -6.500124 dB) */
    0x0805u,   /*   -6.0 dB  ->   0.50122 x   (realised -5.999420 dB) */
    0x087Fu,   /*   -5.5 dB  ->   0.53101 x   (realised -5.498014 dB) */
    0x08FFu,   /*   -5.0 dB  ->   0.56226 x   (realised -5.001320 dB) */
    0x0988u,   /*   -4.5 dB  ->   0.59570 x   (realised -4.499402 dB) */
    0x0A18u,   /*   -4.0 dB  ->   0.63086 x   (realised -4.001349 dB) */
    0x0AB2u,   /*   -3.5 dB  ->   0.66846 x   (realised -3.498530 dB) */
    0x0B54u,   /*   -3.0 dB  ->   0.70801 x   (realised -2.999239 dB) */
    0x0C00u,   /*   -2.5 dB  ->   0.75000 x   (realised -2.498775 dB) */
    0x0CB6u,   /*   -2.0 dB  ->   0.79443 x   (realised -1.998848 dB) */
    0x0D76u,   /*   -1.5 dB  ->   0.84131 x   (realised -1.500893 dB) */
    0x0E43u,   /*   -1.0 dB  ->   0.89136 x   (realised -0.998962 dB) */
    0x0F1Bu,   /*   -0.5 dB  ->   0.94409 x   (realised -0.499716 dB) */
    0x1000u,   /*   +0.0 dB  ->   1.00000 x   (realised +0.000000 dB) */
    0x10F3u,   /*   +0.5 dB  ->   1.05933 x   (realised +0.500594 dB) */
    0x11F4u,   /*   +1.0 dB  ->   1.12207 x   (realised +1.000401 dB) */
    0x1304u,   /*   +1.5 dB  ->   1.18848 x   (realised +1.499812 dB) */
    0x1425u,   /*   +2.0 dB  ->   1.25903 x   (realised +2.000744 dB) */
    0x1556u,   /*   +2.5 dB  ->   1.33350 x   (realised +2.499835 dB) */
    0x169Au,   /*   +3.0 dB  ->   1.41260 x   (realised +3.000370 dB) */
    0x17F1u,   /*   +3.5 dB  ->   1.49634 x   (realised +3.500593 dB) */
    0x195Cu,   /*   +4.0 dB  ->   1.58496 x   (realised +4.000371 dB) */
    0x1ADCu,   /*   +4.5 dB  ->   1.67871 x   (realised +4.499518 dB) */
    0x1C74u,   /*   +5.0 dB  ->   1.77832 x   (realised +5.000200 dB) */
    0x1E23u,   /*   +5.5 dB  ->   1.88354 x   (realised +5.499520 dB) */
    0x1FEDu,   /*   +6.0 dB  ->   1.99536 x   (realised +6.000431 dB) */
    0x21D1u,   /*   +6.5 dB  ->   2.11353 x   (realised +6.500149 dB) */
    0x23D2u,   /*   +7.0 dB  ->   2.23877 x   (realised +7.000188 dB) */
    0x25F1u,   /*   +7.5 dB  ->   2.37134 x   (realised +7.499869 dB) */
    0x2831u,   /*   +8.0 dB  ->   2.51196 x   (realised +8.000264 dB) */
    0x2A92u,   /*   +8.5 dB  ->   2.66064 x   (realised +8.499737 dB) */
    0x2D18u,   /*   +9.0 dB  ->   2.81836 x   (realised +8.999927 dB) */
    0x2FC4u,   /*   +9.5 dB  ->   2.98535 x   (realised +9.499910 dB) */
    0x3299u,   /*  +10.0 dB  ->   3.16235 x   (realised +10.000208 dB) */
    0x3598u,   /*  +10.5 dB  ->   3.34961 x   (realised +10.499883 dB) */
    0x38C5u,   /*  +11.0 dB  ->   3.54810 x   (realised +10.999907 dB) */
    0x3C22u,   /*  +11.5 dB  ->   3.75830 x   (realised +11.499831 dB) */
    0x3FB2u,   /*  +12.0 dB  ->   3.98096 x   (realised +11.999750 dB) */
    0x4379u,   /*  +12.5 dB  ->   4.21704 x   (realised +12.500157 dB) */
    0x4778u,   /*  +13.0 dB  ->   4.46680 x   (realised +12.999924 dB) */
    0x4BB4u,   /*  +13.5 dB  ->   4.73145 x   (realised +13.499876 dB) */
    0x5031u,   /*  +14.0 dB  ->   5.01196 x   (realised +14.000157 dB) */
    0x54F1u,   /*  +14.5 dB  ->   5.30884 x   (realised +14.499989 dB) */
    0x59FAu,   /*  +15.0 dB  ->   5.62354 x   (realised +15.000188 dB) */
    0x5F4Eu,   /*  +15.5 dB  ->   5.95654 x   (realised +15.499886 dB) */
    0x64F4u,   /*  +16.0 dB  ->   6.30957 x   (realised +15.999996 dB) */
    0x6AEFu,   /*  +16.5 dB  ->   6.68335 x   (realised +16.499884 dB) */
    0x7145u,   /*  +17.0 dB  ->   7.07935 x   (realised +16.999862 dB) */
    0x77FCu,   /*  +17.5 dB  ->   7.49902 x   (realised +17.500094 dB) */
    0x7F18u,   /*  +18.0 dB  ->   7.94336 x   (realised +18.000084 dB) */
    0x86A0u,   /*  +18.5 dB  ->   8.41406 x   (realised +18.500115 dB) */
    0x8E9Au,   /*  +19.0 dB  ->   8.91260 x   (realised +19.000086 dB) */
    0x970Du,   /*  +19.5 dB  ->   9.44067 x   (realised +19.500060 dB) */
    0xA000u,   /*  +20.0 dB  ->  10.00000 x   (realised +20.000000 dB) */
    0xA97Bu,   /*  +20.5 dB  ->  10.59253 x   (realised +20.499993 dB) */
    0xB386u,   /*  +21.0 dB  ->  11.22021 x   (realised +21.000023 dB) */
    0xBE29u,   /*  +21.5 dB  ->  11.88501 x   (realised +21.499991 dB) */
    0xC96Eu,   /*  +22.0 dB  ->  12.58936 x   (realised +22.000070 dB) */
    0xD55Du,   /*  +22.5 dB  ->  13.33521 x   (realised +22.499994 dB) */
    0xE202u,   /*  +23.0 dB  ->  14.12549 x   (realised +23.000069 dB) */
    0xEF66u,   /*  +23.5 dB  ->  14.96240 x   (realised +23.500027 dB) */
    0xFD95u,   /*  +24.0 dB  ->  15.84888 x   (realised +23.999970 dB) */
};

#endif /* GAIN_DB_TABLES_H */
