# -*- coding: utf-8 -*-
"""Emit the Type_LB L3 NOISE BANK the CK firmware compiles.

GENERATED FILE -- do not hand-edit the output.

This is the other half of the L3 voice: `L3 = tone + noise(mod_db=1.5)`.  The tone half
is `avas_type_lb_ck_tables.h` (five arrays, two counts, one level).  This half is a
12-band state-variable filter bank fed from one tilted white source, and everything in
it comes from `avas_type_lb_noise_fixed.py` -- the same fit that measured the design.
There is no second copy of a coefficient.

    python tools/gen_avas_type_lb_ck_noise.py [out.h] [seconds]
    (default out: src/app/dsp/avas_type_lb_ck_noise_tables.h, 20 s of measurement)

THREE THINGS THIS GENERATOR DECIDES DIFFERENTLY FROM SECTION 14, each measured here
rather than assumed, and each printed so the header carries the evidence:

  1. 12 BANDS, NOT 13.  The fit puts band 11 (1189-1724 Hz) at gain Q15 = 0 -- the
     solver killed it, because band 10 next door is at full scale and its skirt already
     covers band 11's target.  A zero-gain band contributes nothing to the output and
     still costs its three multiplies every sample, so it is dropped.  MEASURED: the
     output is BIT-IDENTICAL with it removed, which is the only proof that matters.

  2. NO 4TH-ORDER BAND.  Section 14 fits band 12 as two cascaded SVFs, but the
     integer bank in the model never cascaded it -- `run_bank()` ignores `ORD` -- so
     the 1.18 dB the doc reports was already measured WITHOUT the cascade.  Adding it
     was measured here: 1.18 -> 1.21 dB rms, i.e. very slightly worse and well inside
     one realisation's noise.  It costs 15 instructions per sample and buys nothing
     measurable, so it is not spent.  (What this does NOT change: the GAINS are the
     ones fitted against the 4th-order response, which is why the composite is still
     right -- the fit's own error table is unaffected by how the bank is then run.)

  3. THE LEVEL HAS NO FREE PARAMETER, and this is where it gets pinned.  `NG[b]` are
     absolute band rms values in the reference sound's units and the tone's `AMP` are in the
     same units, so the two halves are one sum: the bank's integer output is converted
     to the engine's A_SCALE units by ONE Q15 gain, measured here as `k * A_SCALE`
     where `k` is the counts-to-reference-units scalar the shape fit already uses.
     Nothing is tuned by ear.
"""
import io
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
OUT = (sys.argv[1] if len(sys.argv) > 1
       else os.path.join(ROOT, "src/app/dsp/avas_type_lb_ck_noise_tables.h"))
SECONDS = float(sys.argv[2]) if len(sys.argv) > 2 else 20.0

# ---------------------------------------------------------------------------
# The fit, imported rather than re-derived: exec the model up to its own simulation
# so we get FQ / QQ1 / G / PRE_A and nothing else runs.
# ---------------------------------------------------------------------------
sys.path.insert(0, HERE)
_argv = sys.argv
sys.argv = ["avas_type_lb_noise_fixed.py", "0.1", "13"]
_src = io.open(os.path.join(HERE, "avas_type_lb_noise_fixed.py"), encoding="utf-8").read()
_M = {"__name__": "noise_model",
      "__file__": os.path.join(HERE, "avas_type_lb_noise_fixed.py")}
import contextlib                                                    # noqa: E402
_log = io.StringIO()
with contextlib.redirect_stdout(_log):  # the model's own report is not this tool's job
    exec(compile(_src[:_src.index("N = int(round(SECONDS * FS))")], "noise_model", "exec"),
         _M)
sys.argv = _argv

FS = _M["FS"]
DEC = _M["DEC"]
NB_FIT = _M["NB"]
LO, HI, NG = _M["LO"], _M["HI"], _M["NG"]
NOISE_RMS = _M["NOISE_RMS"]
F_Q15_ALL = np.round(_M["FQ"] * 32768).astype(np.int64)
Q1_Q15 = int(round(_M["QQ1"] * 32768))
G_Q15_ALL = np.round(_M["G"] / max(_M["G"].max(), 1e-30) * 32767).astype(np.int64)
TILT_A_Q15 = int(round(_M["PRE_A"] * 32768))
TILT_POLES = int(_M["PRE_POLES"])
assert TILT_POLES == 1, ("the C runs exactly one tilt pole; the fit chose %d -- "
                         "change the C, do not silently drop poles" % TILT_POLES)

# Decision 1: the live bands are the ones with a non-zero fitted gain.
LIVE = [b for b in range(NB_FIT) if G_Q15_ALL[b] != 0]
DEAD = [b for b in range(NB_FIT) if G_Q15_ALL[b] == 0]
NB = len(LIVE)
F_Q15 = F_Q15_ALL[LIVE]
G_Q15 = G_Q15_ALL[LIVE]

# ---------------------------------------------------------------------------
# The tone's A_SCALE, from the same model the tone tables are generated by -- so the
# two halves cannot drift apart.  MAX_SPAN_HZ = 100 is the shipped Type_LB set
# (design section 12); a different span is a different A_SCALE and therefore a
# different noise gain, which is why it is asserted rather than defaulted.
# ---------------------------------------------------------------------------
os.environ.setdefault("DEC", "32")
os.environ.setdefault("FRACBITS", "16")
os.environ.setdefault("CARRIER", "table")
os.environ["MAX_SPAN_HZ"] = "100.0"
sys.argv = [sys.argv[0], os.path.join(HERE, "L3_params_type_lb.txt"), "0.0"]
import avas_type_ty_fixed_model as TM                                   # noqa: E402
sys.argv = _argv
assert TM.SOURCE_IS_LINE_LIST
A_SCALE = float(TM.A_SCALE)
PEAK_ABS = float(TM.PEAK_ABS)
NORM_GAIN_Q15 = int(TM.OUT_GAIN_Q15)
NORM_SHIFT = int(TM.OUT_SHIFT)


# ---------------------------------------------------------------------------
# The integer bank, EXACTLY as the C will run it, vectorised over bands only -- the
# recursion is over samples, so this stays bit-identical to a scalar loop while being
# fast enough to measure 20 s.
# ---------------------------------------------------------------------------
def run_bank(n, f_q15, g_q15, seed=0x1234567, gusts=True, gust_seed=0xC0FFEE):
    lim = 1 << 15
    nb = len(f_q15)
    lo_s = np.zeros(nb, dtype=np.int64)
    bd_s = np.zeros(nb, dtype=np.int64)
    fq = np.asarray(f_q15, dtype=np.int64)
    gq = np.asarray(g_q15, dtype=np.int64)
    geff = gq.copy()
    out = np.zeros(n, dtype=np.int64)
    x = np.uint32(seed)
    gx = np.uint32(gust_seed)
    pre = 0
    walk = np.zeros(nb, dtype=np.int64)         # the random walk itself, int16-scaled
    for i in range(n):
        if gusts and (i % DEC) == 0:
            for b in range(nb):
                gx ^= np.uint32(gx << np.uint32(13))
                gx ^= np.uint32(gx >> np.uint32(17))
                gx ^= np.uint32(gx << np.uint32(5))
                d = int(np.int16(np.int32(gx) >> 16))
                v = walk[b] + ((GUST_A_Q15 * (d - walk[b])) >> 15)
                walk[b] = max(-GUST_WALK_LIM, min(GUST_WALK_LIM, v))
            m = (GUST_K_Q15 * walk) >> 15       # Q15 fractional gain change
            geff = np.maximum(gq + ((gq * m) >> 15), 0)
        x ^= np.uint32(x << np.uint32(13))
        x ^= np.uint32(x >> np.uint32(17))
        x ^= np.uint32(x << np.uint32(5))
        w = int(np.int16(np.int32(x) >> 16))
        # The tilt, in the form the C can actually run.  The model's own version is
        # `pre += (a * ((w << 15) - pre)) >> 15`, which needs a 16x32 multiply whose
        # product is 43 bits -- it cannot be done in int32 at all, and Python only got
        # away with it by being arbitrary-precision.  This is the leaky integrator:
        # same pole, same unity DC gain, and the difference is a 16x16 multiply.  It is
        # an APPROXIMATION of the one-pole the gains were fitted against, so its cost
        # is paid in the measured shape error below, not assumed to be zero.
        pre += TILT_A_Q15 * (w - (pre >> 15))
        w = pre >> 15
        lo_s += (fq * bd_s) >> 15
        hi = w - lo_s - ((Q1_Q15 * bd_s) >> 15)
        bd_s += (fq * hi) >> 15
        HEAD["lo"] = max(HEAD["lo"], int(np.abs(lo_s).max()))
        HEAD["bd"] = max(HEAD["bd"], int(np.abs(bd_s).max()))
        HEAD["hi"] = max(HEAD["hi"], int(np.abs(hi).max()))
        lo_s = ((lo_s + lim) & (2 * lim - 1)) - lim
        bd_s = ((bd_s + lim) & (2 * lim - 1)) - lim
        acc = (geff * bd_s).sum()
        HEAD["acc"] = max(HEAD["acc"], int(abs(acc)))
        out[i] = acc >> 15
    return out


# Whether the 16-bit state EVER wraps is the whole question behind "16-bit state is
# sufficient": if it does, the noise contains wrap artefacts and the C must widen or
# saturate.  Measured, not assumed.  `hi` is tracked too because it is the one quantity
# that provably exceeds int16 (|w| + |lo| + |Q1*bd| ~ 17 bits), which is what decides
# whether the C's second multiply can stay 16x16.
HEAD = {"lo": 0, "bd": 0, "hi": 0, "acc": 0}


# The gust: a slow random walk per band, one update per DEC samples.  The model drives
# it with a Gaussian and converts dB->linear with a pow(); the ISR can afford neither,
# so the C uses a uniform drive and a first-order 10^(x/20), and the sd that comes out
# is MEASURED below rather than assumed to equal the model's 1.5 dB.
#
#   walk += (A * (uniform_int16 - walk)) >> 15   one-pole at the control rate, clamped
#   m     = (K * walk) >> 15                     Q15 fractional gain change
#   g_eff = g + ((g * m) >> 15)                  1 + ln(10)/20 * 1.5 dB * walk/sd
#
# tau: 1.2 Hz at the control rate, the same pole the model uses.  K is NOT an int16 --
# it is ~6 in Q15, i.e. about 195 000 -- so the C holds it in an int32_t and the clamp
# on `walk` is what keeps `K * walk` inside int32 (worst case 4 sd, ~7.4e8).
_TAU_BLOCKS = FS / DEC / (2.0 * np.pi * 1.2)
GUST_A_Q15 = int(round(32768.0 / max(_TAU_BLOCKS, 1.0)))
# A uniform int16 drive through a one-pole with coefficient a has steady-state sd
# = sd_in * sqrt(a / (2 - a)), sd_in = 32768/sqrt(3).  K maps one sd of `walk` to 1.5 dB.
_A = GUST_A_Q15 / 32768.0
_SD_WALK = (32768.0 / np.sqrt(3.0)) * np.sqrt(_A / (2.0 - _A))
GUST_WALK_LIM = int(round(4.0 * _SD_WALK))
GUST_K_Q15 = int(round((np.log(10.0) / 20.0) * 1.5 / _SD_WALK * 32768.0 * 32768.0))
assert GUST_K_Q15 * GUST_WALK_LIM < (1 << 31), "the gust would overflow int32 in the C"


def measure_gust(ticks=300000, seed=0xC0FFEE):
    """The sd, in dB, of the gain modulation the C actually produces."""
    gx = np.uint32(seed)
    walk = 0
    db = np.zeros(ticks)
    for i in range(ticks):
        gx ^= np.uint32(gx << np.uint32(13))
        gx ^= np.uint32(gx >> np.uint32(17))
        gx ^= np.uint32(gx << np.uint32(5))
        d = int(np.int16(np.int32(gx) >> 16))
        walk = max(-GUST_WALK_LIM,
                   min(GUST_WALK_LIM, walk + ((GUST_A_Q15 * (d - walk)) >> 15)))
        db[i] = 20 * np.log10(max(1.0 + ((GUST_K_Q15 * walk) >> 15) / 32768.0, 1e-6))
    return float(db.std())


GUST_SD_DB = measure_gust()

N = int(round(SECONDS * FS))
print("L3 noise bank -> %s" % os.path.relpath(OUT, ROOT))
print("  fitted bands %d, live %d, dropped (gain Q15 = 0): %s"
      % (NB_FIT, NB, ", ".join("%d (%.0f-%.0f Hz)" % (b, LO[b], HI[b]) for b in DEAD)
         or "none"))

# Decision 1's proof: dropping a zero-gain band must not change one sample.  Gusts OFF,
# and not for convenience -- a dead band still draws from the gust PRNG, so keeping them
# on would compare two different noise realisations and prove nothing either way.  The
# dead band's own modulated gain stays 0 regardless (g_eff = 0 + 0*m), which is exactly
# why its only effect on the output is through that draw order.
_a = run_bank(4096, F_Q15_ALL[:NB_FIT], G_Q15_ALL[:NB_FIT], gusts=False)
_b = run_bank(4096, F_Q15, G_Q15, gusts=False)
assert np.array_equal(_a, _b), "dropping the zero-gain band CHANGED the output"
print("  dropping the dead band is bit-identical over 4096 samples: PROVEN")

HEAD.update(lo=0, bd=0, hi=0, acc=0)
y = run_bank(N, F_Q15, G_Q15)
# What follows is OBSERVED peaks over one realisation, which is not the same thing as a
# bound -- so each is reported with the margin it leaves, and the C's choice of width is
# made from the arithmetic bound where one exists.
hard_hi = 32767 + HEAD["lo"] + ((Q1_Q15 * HEAD["bd"]) >> 15)
print("  over %.0f s, observed peak / limit:" % SECONDS)
print("      |low| %6d, |band| %6d  of 32767  -> the int16_t state %s"
      % (HEAD["lo"], HEAD["bd"],
         "never wraps (margin %.2fx)" % (32767.0 / max(HEAD["lo"], HEAD["bd"], 1))
         if max(HEAD["lo"], HEAD["bd"]) <= 32767 else
         "DOES wrap -- the sound is not what was fitted"))
print("      |high| %6d  of 32767, but its arithmetic BOUND is %d: held in int32_t, "
      "because a\n              1.%02dx observed margin is not a bound and a wrap here "
      "is a full-scale\n              impulse in a noise signal."
      % (HEAD["hi"], hard_hi, int(round((32767.0 / HEAD["hi"] - 1.0) * 100))))
print("      |acc| %9d of 2147483647 (margin %.1fx) -- the one genuinely unbounded\n"
      "              quantity, 12 correlated bandpasses summed before the >>15."
      % (HEAD["acc"], 2147483647.0 / max(HEAD["acc"], 1)))
w = np.hanning(len(y))
cal = np.sqrt(2.0) / (len(y) * np.sqrt(np.mean(w ** 2)))
S = np.abs(np.fft.rfft(y * w)) * cal
f = np.fft.rfftfreq(len(y), 1.0 / FS)
lv = np.array([np.sqrt(np.sum(S[(f >= LO[b]) & (f < HI[b])] ** 2)) for b in range(NB_FIT)])
# k: counts -> the reference sound's units.  One scalar, least squares against the targets --
# the same estimator the model's shape check uses, and the ONLY thing that sets the
# noise level relative to the tone.
K_CNT = float(np.sum(lv * NG[:NB_FIT]) / max(np.sum(lv * lv), 1e-30))
e_db = 20 * np.log10(np.maximum(lv * K_CNT, 1e-30) / np.maximum(NG[:NB_FIT], 1e-30))
PEAK_CNT = int(np.abs(y).max())
RMS_CNT = float(y.std())

print("  %.0f s: shape error mean %+.2f worst %+.2f rms %.2f dB   peak %d rms %.0f counts"
      % (SECONDS, e_db.mean(), e_db[np.argmax(np.abs(e_db))],
         np.sqrt((e_db ** 2).mean()), PEAK_CNT, RMS_CNT))
print("  gust: a = %d/32768 (tau %.1f blocks = 1.2 Hz), k = %d, walk clamp +-%d"
      % (GUST_A_Q15, _TAU_BLOCKS, GUST_K_Q15, GUST_WALK_LIM))
print("        MEASURED sd %.2f dB against the model's 1.5 dB" % GUST_SD_DB)

# ---------------------------------------------------------------------------
# THE LEVEL, and the headroom question it raises.
# ---------------------------------------------------------------------------
GAIN_LIN = K_CNT * A_SCALE                     # counts -> the engine's A_SCALE units
GAIN_SHIFT = 0
while GAIN_SHIFT < 15 and int(round(GAIN_LIN / 2.0 ** GAIN_SHIFT * 32768.0)) > 32767:
    GAIN_SHIFT += 1
GAIN_Q15 = int(round(GAIN_LIN / 2.0 ** GAIN_SHIFT * 32768.0))
noise_rms_as = RMS_CNT * GAIN_LIN
noise_peak_as = PEAK_CNT * GAIN_LIN
tone_peak_as = PEAK_ABS * A_SCALE
out_gain = NORM_GAIN_Q15 / 32768.0 * (2.0 ** NORM_SHIFT)

print("\nlevel, with no free parameter:")
print("  counts -> reference units  k = %.6e   (noise rms %.6e vs the table's %.6e)"
      % (K_CNT, RMS_CNT * K_CNT, NOISE_RMS))
print("  noise/tone = %+.2f dB (the table says -17.85 dB)"
      % (20 * np.log10(RMS_CNT * K_CNT / 2.106063317e-01)))
print("  A_SCALE = %.1f, so the bank's gain is %.6f = %d >> %d"
      % (A_SCALE, GAIN_LIN, GAIN_Q15, 15 + GAIN_SHIFT))
print("\nheadroom, in A_SCALE units before the output gain of %.4f:" % out_gain)
print("  tone peak (60 s, measured)      %8.0f" % tone_peak_as)
print("  noise peak (%.0f s, measured)     %8.0f" % (SECONDS, noise_peak_as))
print("  worst-case sum                  %8.0f  -> after gain %8.0f  (full scale 32767)"
      % (tone_peak_as + noise_peak_as, (tone_peak_as + noise_peak_as) * out_gain))
CLIPS = (tone_peak_as + noise_peak_as) * out_gain > 32767.0
print("  => the sum CAN exceed full scale: the type_lb output path MUST clamp, not wrap"
      if CLIPS else "  => fits: no clamp needed")

# ---------------------------------------------------------------------------
# The header.
# ---------------------------------------------------------------------------
def rows(vals, per_line, fmt):
    out = []
    for i in range(0, len(vals), per_line):
        out.append("    " + " ".join(fmt % v for v in vals[i:i + per_line]))
    return "\n".join(out)


band_rows = "\n".join(
    " *   %2d  %6.0f-%6.0f Hz   F %5d   gain %5d   err %+5.2f dB"
    % (b, LO[b], HI[b], F_Q15_ALL[b], G_Q15_ALL[b], e_db[b]) for b in LIVE)

H = '''/*
 * avas_type_lb_ck_noise_tables.h -- the L3 voice's NOISE half, GENERATED.
 *
 * GENERATED by tools/gen_avas_type_lb_ck_noise.py -- DO NOT EDIT.  Every integer here is
 * measured by tools/avas_type_lb_noise_fixed.py (design section 14) and re-measured on
 * the exact integer arithmetic avas_noise_bank_ck.c runs.
 *
 * WHAT THIS IS: one white source, tilted once by a single Q15 one-pole, feeding %(nb)d
 * Chamberlin state-variable bandpasses whose outputs are summed with fitted gains.
 * NOT a bank of direct-form biquads: at the lowest band's %(locentre).0f Hz centre a Q14 `a1`
 * quantises the pole ANGLE by 100%%, i.e. the centre frequency becomes arbitrary.  The
 * SVF tunes on F = 2 sin(pi f0 / fs), which at that centre is 0.3%% off.
 *
 * BANDS, and why there are %(nb)d and not %(nbfit)d.  The fit put band 11 (1189-1724 Hz) at
 * gain Q15 = 0 -- band 10 is at full scale next door and its skirt already covers
 * band 11's target.  A zero-gain band cannot contribute to the output but still costs
 * three multiplies a sample, so it is not built.  The generator PROVES the removal is
 * bit-identical before emitting this file.
 *
%(bands)s
 *
 * MEASURED over %(secs).0f s of this arithmetic: band-level shape error mean %(emean)+.2f dB,
 * worst %(eworst)+.2f dB, rms %(erms).2f dB; peak |y| %(peak)d counts, rms %(rms).0f counts.
 *
 * THE LEVEL IS NOT A TUNING KNOB.  NG[b] and the tone's AMP[] are both in the
 * reference sound's units, so tone + noise is a sum with nothing free in it: the bank's
 * counts are converted to the engine's A_SCALE units by AVAS_TYPE_LB_CK_NOISE_GAIN_Q15
 * >> AVAS_TYPE_LB_CK_NOISE_GAIN_SHIFT, measured as k * A_SCALE = %(k).6e * %(ascale).1f.
 * The realised noise/tone ratio is %(ratio)+.2f dB against the table's -17.85 dB.
 */
#ifndef AVAS_TYPE_LB_CK_NOISE_TABLES_H
#define AVAS_TYPE_LB_CK_NOISE_TABLES_H

#include <stdint.h>

#define AVAS_TYPE_LB_CK_NOISE_BANDS           (%(nb)du)

/* 1/Q in Q15, SHARED by every band: the bands are geometric with a common ratio, so
 * they have a common Q -- which is what makes the -3 dB edges land on the band edges. */
#define AVAS_TYPE_LB_CK_NOISE_Q1_Q15          (%(q1)d)

/* The source tilt: ONE Q15 one-pole at %(tiltfc).0f Hz, `y += (a*(x-y)) >> 15`.  It exists
 * because a 2nd-order skirt falls at 6 dB/octave and this target falls at
 * 12.4 dB/octave, so no vector of gains can fix it -- fitting white-driven bands left
 * five gains at zero and the composite was still +27 dB too loud at 9 kHz.  Tilting the
 * SOURCE costs 3-4 instructions ONCE for the whole bank. */
#define AVAS_TYPE_LB_CK_NOISE_TILT_A_Q15      (%(tilt)d)

/* Counts -> the engine's A_SCALE units.  See the level note above. */
#define AVAS_TYPE_LB_CK_NOISE_GAIN_Q15        (%(gain)d)
#define AVAS_TYPE_LB_CK_NOISE_GAIN_SHIFT      (%(gshift)d)

/* The gust: L3 is `tone + noise(mod_db=1.5)`, and the 1.5 dB is a slow per-band random
 * walk at 1.2 Hz -- it moves energy around in time without changing any band's
 * long-term rms.  Updated once per DEC samples, so it costs NOTHING per sample: the
 * modulated gain is folded into the same coefficient the bank already multiplies by.
 *
 * The model drives the walk with a Gaussian and converts dB to linear with pow(); the
 * ISR can afford neither, so this is a uniform drive and a first-order 10^(x/20).  The
 * sd that comes out is MEASURED (%(gustsd).2f dB against the model's 1.5 dB) rather than
 * assumed equal. */
#define AVAS_TYPE_LB_CK_NOISE_GUST_A_Q15      (%(gusta)d)
/* NOT an int16: ~6.0 in Q15.  The clamp is what keeps `K * walk` inside int32. */
#define AVAS_TYPE_LB_CK_NOISE_GUST_K_Q15      (%(gustk)dL)
#define AVAS_TYPE_LB_CK_NOISE_GUST_WALK_LIM   (%(gustlim)d)

/* The white source is the xorshift32 sonora's Type_LB uses, from the same seed, so
 * the two boards' noise is comparable rather than merely similar. */
#define AVAS_TYPE_LB_CK_NOISE_SEED            (0x1234567uL)
#define AVAS_TYPE_LB_CK_NOISE_GUST_SEED       (0xC0FFEEuL)

/* F = 2 sin(pi f0 / fs) in Q15, one per band. */
static const int16_t s_ck_type_lb_noise_f_q15[AVAS_TYPE_LB_CK_NOISE_BANDS] = {
%(frows)s
};

/* The fitted gains in Q15, normalised so the loudest band is full scale.  Fitted on the
 * COHERENT sum |sum_b g_b H_b(f)|, not a power sum, because one shared white source
 * means overlapping skirts add with their phases. */
static const int16_t s_ck_type_lb_noise_g_q15[AVAS_TYPE_LB_CK_NOISE_BANDS] = {
%(grows)s
};

#endif /* AVAS_TYPE_LB_CK_NOISE_TABLES_H */
''' % {
    "nb": NB, "nbfit": NB_FIT, "bands": band_rows, "secs": SECONDS,
    "emean": e_db.mean(), "eworst": e_db[np.argmax(np.abs(e_db))],
    "erms": np.sqrt((e_db ** 2).mean()), "peak": PEAK_CNT, "rms": RMS_CNT,
    "k": K_CNT, "ascale": A_SCALE,
    "ratio": 20 * np.log10(RMS_CNT * K_CNT / 2.106063317e-01),
    "q1": Q1_Q15, "tilt": TILT_A_Q15, "tiltfc": _M["PRE_FC"],
    "gain": GAIN_Q15, "gshift": 15 + GAIN_SHIFT,
    "gusta": GUST_A_Q15, "gustk": GUST_K_Q15, "gustlim": GUST_WALK_LIM,
    "gustsd": GUST_SD_DB, "locentre": float(np.sqrt(LO[0] * HI[0])),
    "frows": rows([int(v) for v in F_Q15], 8, "%6d,"),
    "grows": rows([int(v) for v in G_Q15], 8, "%6d,"),
}

io.open(OUT, "w", encoding="utf-8", newline="\r\n").write(H)
print("\nwrote %s (%d bands, %d bytes of const)" % (os.path.relpath(OUT, ROOT), NB, NB * 4))

# The reference vector the host check compares the C against, gusts OFF so it is a pure
# function of the arithmetic: gusts need a PRNG the two languages cannot share bit for
# bit, and their sd is checked separately.
REF = os.path.join(HERE, "host_check", "type_lb_noise_ref.txt")
ref = run_bank(4096, F_Q15, G_Q15, gusts=False)
# In the SAME units avas_noise_bank_ck_sample() returns: the gain is applied here too, so
# the comparison covers the level and not merely the filters.  Python's >> floors and so
# does the C's arithmetic shift on this compiler, which is why this is a shift and not a
# division.
ref = (ref * GAIN_Q15) >> (15 + GAIN_SHIFT)
assert int(np.abs(ref).max()) <= 32767, "the reference does not fit int16_t"
io.open(REF, "w", encoding="utf-8", newline="\n").write(
    "".join("%d\n" % v for v in ref))
print("wrote %s (4096 samples, gusts off, gain applied)" % os.path.relpath(REF, ROOT))
